from django.urls import path

from . import views

app_name = "estoque"

urlpatterns = [
    path("", views.EstoqueListView.as_view(), name="lista"),
    path("lotes/", views.LoteEstoqueListView.as_view(), name="lotes"),
    path("lotes/reconciliacao/", views.reconciliacao_lotes, name="reconciliacao_lotes"),
    path("lotes/reconciliacao/<int:pk>/atribuir/", views.atribuir_saldo_lote, name="atribuir_saldo_lote"),
    path("movimentar/", views.movimentar, name="movimentar"),
    path("inventarios/", views.InventarioListView.as_view(), name="inventarios"),
    path("inventarios/novo/", views.CriarInventarioView.as_view(), name="inventario_novo"),
    path("inventarios/<int:pk>/", views.inventario_detalhe, name="inventario_detalhe"),
    path("inventarios/<int:pk>/itens/novo/", views.adicionar_item_inventario, name="inventario_item_novo"),
    path("inventarios/<int:pk>/aplicar/", views.aplicar_inventario_view, name="inventario_aplicar"),
    path("perdas/", views.PerdaEstoqueListView.as_view(), name="perdas"),
    path("perdas/nova/", views.registrar_perda, name="perda_nova"),
    path("receitas-desmembramento/", views.ReceitaDesmembramentoListView.as_view(), name="receitas_desmembramento"),
    path("receitas-desmembramento/nova/", views.ReceitaDesmembramentoCreateView.as_view(), name="receita_desmembramento_nova"),
    path("receitas-desmembramento/<int:pk>.json", views.receita_desmembramento_json, name="receita_desmembramento_json"),
    path("receitas-desmembramento/<int:pk>/editar/", views.ReceitaDesmembramentoUpdateView.as_view(), name="receita_desmembramento_editar"),
    path("produtos/busca.json", views.produtos_busca, name="produtos_busca"),
    path("composicoes/", views.ComposicaoProdutoListView.as_view(), name="composicoes"),
    path("composicoes/exportar.csv", views.composicoes_csv, name="composicoes_csv"),
    path("composicoes/programar-sugestoes/", views.composicoes_programar_sugestoes, name="composicoes_programar_sugestoes"),
    path("composicoes/producoes/relatorio/", views.composicao_producoes_relatorio, name="composicao_producoes_relatorio"),
    path("composicoes/producoes/relatorio/exportar.csv", views.composicao_producoes_relatorio_csv, name="composicao_producoes_relatorio_csv"),
    path("composicoes/slas-setor/", views.ConfiguracaoSLASetorProducaoListView.as_view(), name="slas_setor_producao"),
    path("composicoes/slas-setor/nova/", views.ConfiguracaoSLASetorProducaoCreateView.as_view(), name="sla_setor_producao_novo"),
    path("composicoes/slas-setor/<int:pk>/editar/", views.ConfiguracaoSLASetorProducaoUpdateView.as_view(), name="sla_setor_producao_editar"),
    path("composicoes/alertas-sla/", views.alertas_sla_producao, name="alertas_sla_producao"),
    path("composicoes/alertas-sla/<int:pk>/visualizar/", views.alerta_sla_producao_visualizar, name="alerta_sla_producao_visualizar"),
    path("composicoes/ordens/", views.OrdemProducaoComposicaoListView.as_view(), name="ordens_producao_composicao"),
    path("composicoes/ordens/fila/", views.ordens_producao_composicao_fila, name="ordens_producao_composicao_fila"),
    path("composicoes/ordens/exportar.csv", views.ordens_producao_composicao_csv, name="ordens_producao_composicao_csv"),
    path("composicoes/ordens/nova/", views.ordem_producao_composicao_nova, name="ordem_producao_composicao_nova"),
    path("composicoes/ordens/<int:pk>/imprimir/", views.ordem_producao_composicao_imprimir, name="ordem_producao_composicao_imprimir"),
    path("composicoes/ordens/<int:pk>/etapa/", views.ordem_producao_composicao_etapa, name="ordem_producao_composicao_etapa"),
    path("composicoes/ordens/<int:pk>/confirmar/", views.ordem_producao_composicao_confirmar, name="ordem_producao_composicao_confirmar"),
    path("composicoes/ordens/<int:pk>/cancelar/", views.ordem_producao_composicao_cancelar, name="ordem_producao_composicao_cancelar"),
    path("composicoes/nova/", views.composicao_nova, name="composicao_nova"),
    path("composicoes/<int:pk>/", views.composicao_detalhe, name="composicao_detalhe"),
    path("composicoes/<int:pk>/editar/", views.composicao_editar, name="composicao_editar"),
    path("composicoes/<int:pk>/produzir/", views.composicao_produzir, name="composicao_produzir"),
    path("composicoes/producoes/<int:pk>/cancelar/", views.composicao_cancelar_producao, name="composicao_cancelar_producao"),
    path("desmembramentos/", views.DesmembramentoProdutoListView.as_view(), name="desmembramentos"),
    path("desmembramentos/exportar.csv", views.desmembramentos_csv, name="desmembramentos_csv"),
    path("desmembramentos/relatorio/", views.desmembramento_relatorio, name="desmembramento_relatorio"),
    path("desmembramentos/relatorio/exportar.csv", views.desmembramento_relatorio_csv, name="desmembramento_relatorio_csv"),
    path("desmembramentos/novo/", views.desmembramento_novo, name="desmembramento_novo"),
    path("desmembramentos/<int:pk>/", views.desmembramento_detalhe, name="desmembramento_detalhe"),
    path("desmembramentos/<int:pk>/cancelar/", views.desmembramento_cancelar, name="desmembramento_cancelar"),
]
