# Generated by Django 6.0.6 on 2026-07-31 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NFC', 'NFC / MIFARE'), ('MAGNETICA', 'Cartão magnético'), ('CODIGO_BARRAS', 'Código de barras')], max_length=20)),
                ('nome', models.CharField(help_text='Ex.: crachá do gerente ou cartão do supervisor.', max_length=80)),
                ('identificador_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('pin_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('valida_ate', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credenciais_autorizacao_criadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credenciais_autorizacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial de autorização',
                'verbose_name_plural': 'Credenciais de autorização',
                'ordering': ['-ativa', 'usuario__username', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='UsoCredencialAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usado_em', models.DateTimeField(auto_now_add=True)),
                ('credencial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='accounts.credencialautorizacao')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_autorizadas_por_credencial', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_por_credencial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de credencial de autorização',
                'verbose_name_plural': 'Usos de credenciais de autorização',
                'ordering': ['-usado_em'],
            },
        ),
    ]
