# Generated by Django 6.0.6 on 2026-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_credencialautorizacao_usocredencialautorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usocredencialautorizacao',
            name='acao',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
