# Generated by Django 6.0.6 on 2026-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usocredencialautorizacao_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GERENTE', 'Gerente'), ('OPERADOR_CAIXA', 'Operador de caixa'), ('ESTOQUISTA', 'Estoquista'), ('COMPRAS', 'Compras'), ('FINANCEIRO', 'Financeiro'), ('CONTABILIDADE', 'Contabilidade')], default='OPERADOR_CAIXA', max_length=30),
        ),
    ]
