# Generated by Django 6.0.6 on 2026-06-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CUPOM_NAO_FISCAL', 'Cupom nao fiscal'), ('CUPOM_FISCAL', 'Cupom fiscal'), ('PEDIDO_SEPARACAO', 'Pedido de separacao'), ('ETIQUETA', 'Etiqueta'), ('RELATORIO', 'Relatorio'), ('FECHAMENTO_CAIXA', 'Fechamento de caixa')], max_length=40)),
                ('modelo_papel', models.CharField(choices=[('58MM', 'Bobina 58 mm'), ('80MM', 'Bobina 80 mm'), ('A4', 'A4')], default='80MM', max_length=10)),
                ('exibir_logo', models.BooleanField(default=True)),
                ('tamanho_fonte', models.PositiveIntegerField(default=10)),
                ('margem_superior_mm', models.PositiveIntegerField(default=5)),
                ('margem_inferior_mm', models.PositiveIntegerField(default=5)),
                ('margem_esquerda_mm', models.PositiveIntegerField(default=5)),
                ('margem_direita_mm', models.PositiveIntegerField(default=5)),
                ('mensagem_rodape', models.TextField(blank=True)),
                ('impressora_padrao', models.CharField(blank=True, max_length=255)),
                ('impressao_automatica', models.BooleanField(default=False)),
                ('numero_vias', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_impressao', to='empresas.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_impressao', to='empresas.filial')),
            ],
            options={
                'unique_together': {('empresa', 'filial', 'tipo_documento')},
            },
        ),
    ]
