# Generated by Django 6.0.6 on 2026-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='abrir_gaveta_em_dinheiro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='abrir_gaveta_em_movimento_caixa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='gaveta_automatica',
            field=models.BooleanField(default=False),
        ),
    ]
