# Generated by Django 6.0.6 on 2026-07-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configuracaoimpressao_abrir_gaveta_em_dinheiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='altura_etiqueta_mm',
            field=models.DecimalField(blank=True, decimal_places=2, default=30, max_digits=6),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='colunas_etiqueta',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='densidade_impressao',
            field=models.PositiveSmallIntegerField(blank=True, default=8),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='dpi_impressora',
            field=models.PositiveSmallIntegerField(blank=True, default=203),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='gap_horizontal_mm',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='gap_vertical_mm',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='largura_etiqueta_mm',
            field=models.DecimalField(blank=True, decimal_places=2, default=110, max_digits=6),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='linguagem_impressora',
            field=models.CharField(blank=True, choices=[('WINDOWS', 'Driver do Windows'), ('ZPL', 'ZPL (Zebra)'), ('EPL', 'EPL (Zebra/Eltron)'), ('PPLA', 'PPLA (Argox)'), ('PPLB', 'PPLB (Argox)')], default='WINDOWS', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='tipo_midia_etiqueta',
            field=models.CharField(blank=True, choices=[('GAP', 'Etiqueta com gap'), ('CONTINUA', 'Midia continua'), ('MARCA_PRETA', 'Marca preta')], default='GAP', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='velocidade_impressao',
            field=models.PositiveSmallIntegerField(blank=True, default=4),
        ),
    ]
