# Generated by Django 6.0.6 on 2026-07-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_configuracaoimpressao_altura_etiqueta_mm_and_more'),
        ('pdv', '0009_terminalpdv_licenca_liberada_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('largura_mm', models.DecimalField(decimal_places=2, default=110, max_digits=6)),
                ('altura_mm', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('gap_horizontal_mm', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('gap_vertical_mm', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('colunas', models.PositiveSmallIntegerField(default=1)),
                ('orientacao', models.CharField(choices=[('RETRATO', 'Retrato'), ('PAISAGEM', 'Paisagem')], default='PAISAGEM', max_length=10)),
                ('padrao', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_etiqueta', to='configuracoes.configuracaoimpressao')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_etiqueta', to='pdv.terminalpdv')),
            ],
            options={
                'ordering': ['configuracao__empresa_id', 'configuracao__filial_id', 'nome'],
                'unique_together': {('configuracao', 'nome')},
            },
        ),
    ]
