# Generated by Django 6.0.6 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_modeloetiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='tipo_documento',
            field=models.CharField(choices=[('CUPOM_NAO_FISCAL', 'Cupom não fiscal'), ('CUPOM_FISCAL', 'Cupom fiscal'), ('PEDIDO_SEPARACAO', 'Pedido de separação'), ('ETIQUETA', 'Etiqueta'), ('RELATORIO', 'Relatorio'), ('FECHAMENTO_CAIXA', 'Fechamento de caixa')], max_length=40),
        ),
    ]
