# Generated by Django 6.0.6 on 2026-08-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_alter_configuracaoimpressao_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomologacaoServidorLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(max_length=120)),
                ('sistema_operacional', models.CharField(max_length=120)),
                ('versao_artefato', models.CharField(max_length=50)),
                ('hash_evidencia', models.CharField(max_length=64, unique=True)),
                ('resultado', models.CharField(choices=[('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], max_length=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homologacoes_servidor_local', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'homologação de servidor local',
                'verbose_name_plural': 'homologações de servidor local',
                'ordering': ['-criada_em', '-id'],
            },
        ),
    ]
