# Generated by Django 6.0.6 on 2026-08-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_homologacaoservidorlocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologacaoservidorlocal',
            name='itens_validados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
