# Generated by Django 6.0.6 on 2026-08-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0007_homologacaoservidorlocal_itens_validados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='tipo_documento',
            field=models.CharField(choices=[('CUPOM_NAO_FISCAL', 'Cupom não fiscal'), ('CUPOM_FISCAL', 'Cupom fiscal'), ('PEDIDO_SEPARACAO', 'Pedido de separação'), ('ETIQUETA', 'Etiqueta'), ('RELATORIO', 'Relatório'), ('FECHAMENTO_CAIXA', 'Fechamento de caixa')], max_length=40),
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='tipo_midia_etiqueta',
            field=models.CharField(blank=True, choices=[('GAP', 'Etiqueta com gap'), ('CONTINUA', 'Mídia contínua'), ('MARCA_PRETA', 'Marca preta')], default='GAP', max_length=20),
        ),
    ]
