from django.urls import path

from . import views

app_name = "fiscal"

urlpatterns = [
    path("devolucoes-fornecedor/revisao/<int:pk>/composicao/", views.registrar_composicao_devolucao, name="registrar_composicao_devolucao"),
    path("devolucoes-fornecedor/revisao/<int:pk>/transporte/", views.registrar_transporte_devolucao, name="registrar_transporte_devolucao"),
    path("", views.documentos, name="documentos"),
    path(
        "devolucoes-fornecedor/revisao/",
        views.revisoes_devolucao_fornecedor,
        name="revisoes_devolucao",
    ),
    path(
        "devolucoes-fornecedor/revisao/<int:pk>/",
        views.revisao_devolucao_fornecedor_detalhe,
        name="revisao_devolucao_detalhe",
    ),
    path(
        "devolucoes-fornecedor/revisao/<int:pk>/decidir/",
        views.decidir_revisao_devolucao_fornecedor,
        name="decidir_revisao_devolucao",
    ),
    path(
        "devolucoes-fornecedor/revisao/<int:pk>/parecer/",
        views.registrar_parecer_devolucao_fornecedor,
        name="registrar_parecer_devolucao",
    ),
    path(
        "devolucoes-fornecedor/revisao/<int:pk>/parametros-itens/",
        views.registrar_parametrizacao_devolucao_fornecedor,
        name="registrar_parametrizacao_devolucao",
    ),
    path(
        "devolucoes-fornecedor/revisao/<int:pk>/memoria-calculo/",
        views.registrar_memoria_calculo_devolucao,
        name="registrar_memoria_calculo_devolucao",
    ),
    path(
        "devolucoes-fornecedor/revisao/<int:pk>/memoria-calculo/revisar/",
        views.revisar_memoria_calculo_devolucao,
        name="revisar_memoria_calculo_devolucao",
    ),
    path("atualizacoes/", views.atualizacoes_fiscais, name="atualizacoes"),
    path("atualizacoes/<int:pk>/revisar/", views.revisar_atualizacao_fiscal, name="revisar_atualizacao"),
    path("inutilizacoes/", views.inutilizacoes, name="inutilizacoes"),
    path("consulta-cadastro/", views.consulta_cadastro, name="consulta_cadastro"),
    path("consulta-cadastro/<int:pk>/<str:direcao>/xml/", views.baixar_xml_consulta_cadastro, name="baixar_xml_consulta_cadastro"),
    path("diagnostico.json", views.diagnostico_json, name="diagnostico_json"),
    path("contingencia.json", views.contingencia_json, name="contingencia_json"),
    path("produtos/", views.produtos_fiscais, name="produtos_fiscais"),
    path("dfe-recebidos/", views.dfe_recebidos, name="dfe_recebidos"),
    path("dfe-recebidos/consultar/", views.dfe_consultar_distribuicao, name="dfe_consultar_distribuicao"),
    path("dfe-recebidos/<int:pk>/", views.dfe_detalhe, name="dfe_detalhe"),
    path("dfe-recebidos/<int:pk>/xml/", views.dfe_baixar_xml, name="dfe_baixar_xml"),
    path("dfe-recebidos/<int:pk>/manifestar/", views.dfe_manifestar, name="dfe_manifestar"),
    path(
        "dfe-recebidos/manifestacoes/<int:pk>/<str:direcao>/xml/",
        views.dfe_manifestacao_baixar_xml,
        name="dfe_manifestacao_baixar_xml",
    ),
    path("dfe-recebidos/eventos/<int:pk>/xml/", views.dfe_evento_baixar_xml, name="dfe_evento_baixar_xml"),
    path("dfe-recebidos/<int:pk>/ignorar/", views.dfe_ignorar, name="dfe_ignorar"),
    path(
        "dfe-recebidos/<int:pk>/criar-entrada/",
        views.dfe_criar_entrada,
        name="dfe_criar_entrada",
    ),
    path(
        "produtos/exportar.csv",
        views.produtos_fiscais_exportar_csv,
        name="produtos_fiscais_exportar_csv",
    ),
    path("configuracoes/nova/", views.configuracao_form, name="configuracao_nova"),
    path("configuracoes/<int:pk>/editar/", views.configuracao_form, name="configuracao_editar"),
    path("configuracoes/<int:pk>/homologacao-goias/", views.homologacao_goias, name="homologacao_goias"),
    path("series/nova/", views.serie_form, name="serie_nova"),
    path("series/<int:pk>/editar/", views.serie_form, name="serie_editar"),
    path("naturezas/nova/", views.natureza_form, name="natureza_nova"),
    path("naturezas/<int:pk>/editar/", views.natureza_form, name="natureza_editar"),
    path("naturezas/<int:pk>/definir-padrao/", views.definir_natureza_padrao, name="natureza_definir_padrao"),
    path("vendas/<int:venda_id>/preparar/", views.preparar_venda, name="preparar_venda"),
    path("documentos/<int:pk>/", views.detalhe, name="detalhe"),
    path("documentos/<int:pk>/imprimir/", views.imprimir, name="imprimir"),
    path("documentos/<int:pk>/xml/", views.baixar_xml, name="baixar_xml"),
    path("documentos/<int:pk>/reagendar/", views.reagendar_transmissao, name="reagendar_transmissao"),
    path("documentos/<int:pk>/retomar-consultas-sefaz/", views.retomar_consultas_sefaz, name="retomar_consultas_sefaz"),
    path("documentos/<int:pk>/transmitir-simulado/", views.transmitir_simulado, name="transmitir_simulado"),
    path("documentos/<int:pk>/transmitir-sefaz/", views.transmitir_sefaz, name="transmitir_sefaz"),
    path("documentos/<int:pk>/consultar-sefaz/", views.consultar_sefaz, name="consultar_sefaz"),
    path("documentos/<int:pk>/contingencia/", views.ativar_contingencia, name="ativar_contingencia"),
    path("documentos/<int:pk>/contingencia-svc/", views.ativar_svc, name="ativar_svc"),
    path("documentos/<int:pk>/cancelar/", views.cancelar, name="cancelar"),
    path("documentos/<int:pk>/carta-correcao/", views.registrar_cce, name="registrar_cce"),
    path(
        "cartas-correcao/<int:pk>/<str:direcao>/xml/",
        views.baixar_xml_cce,
        name="baixar_xml_cce",
    ),
]
