# Generated by Django 6.0.6 on 2026-06-30 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('produtos', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CONVERTIDA', 'Convertida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('convertida_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_vendas', to='clientes.cliente')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_vendas', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_vendas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_venda_origem', to='vendas.venda')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPreVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('pre_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='vendas.prevenda')),
            ],
        ),
    ]
