# Generated by Django 6.0.6 on 2026-07-06 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_lancamentofinanceiro_pagamento_venda'),
        ('vendas', '0005_pagamentovenda_estorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='conta_movimento_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento_padrao', to='financeiro.contamovimentofinanceiro'),
        ),
    ]
