# Generated by Django 6.0.6 on 2026-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_formapagamento_conta_movimento_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='documento_consumidor',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='venda',
            name='documento_consumidor_tipo',
            field=models.CharField(choices=[('NAO_IDENTIFICADO', 'Nao identificado'), ('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('ESTRANGEIRO', 'Documento estrangeiro')], default='NAO_IDENTIFICADO', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacao_fiscal_consumidor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
