# Generated by Django 6.0.6 on 2026-07-27 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_venda_documento_consumidor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstornoParcialPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('transacao_estorno_id', models.CharField(blank=True, max_length=120)),
                ('codigo_autorizacao', models.CharField(blank=True, max_length=60)),
                ('mensagem_processadora', models.CharField(blank=True, max_length=255)),
                ('solicitado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos_pagamentos', to='vendas.devolucaovenda')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos_parciais', to='vendas.pagamentovenda')),
                ('usuario_confirmacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estornos_parciais_confirmados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['solicitado_em', 'id'],
                'constraints': [models.UniqueConstraint(fields=('pagamento', 'devolucao'), name='vendas_estorno_parcial_pagamento_devolucao_unico')],
            },
        ),
    ]
