# Generated by Django 6.0.6 on 2026-07-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_alter_eventoentradasincronizacao_status_and_more'),
        ('financeiro', '0008_exportacaocontabil'),
        ('vendas', '0009_formas_pagamento_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamentoFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_movimento_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_formas_pagamento_filial', to='financeiro.contamovimentofinanceiro')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_formas_pagamento', to='empresas.filial')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_filial', to='vendas.formapagamento')),
            ],
            options={
                'ordering': ['filial__empresa__nome_fantasia', 'filial__nome', 'forma_pagamento__nome'],
                'constraints': [models.UniqueConstraint(fields=('filial', 'forma_pagamento'), name='vendas_forma_pagamento_filial_unica')],
            },
        ),
    ]
