# Generated by Django 6.0.6 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_inicializar_formas_pagamento_filiais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='documento_consumidor_tipo',
            field=models.CharField(choices=[('NAO_IDENTIFICADO', 'Não identificado'), ('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('ESTRANGEIRO', 'Documento estrangeiro')], default='NAO_IDENTIFICADO', max_length=20),
        ),
    ]
