# Generated by Django 6.0.6 on 2026-09-23 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0013_alter_terminalpdv_modo_integracao_tef_and_more'),
        ('vendas', '0013_pagamentovenda_dados_fiscais_eletronicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacaoPagamentoIntegrado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_forma', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provedor', models.CharField(max_length=60)),
                ('transacao_externa_id', models.CharField(max_length=120)),
                ('dados', models.JSONField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdv.caixa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento')),
            ],
        ),
        migrations.AddField(
            model_name='pagamentovenda',
            name='confirmacao_integracao',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='vendas.confirmacaopagamentointegrado'),
        ),
        migrations.AddConstraint(
            model_name='confirmacaopagamentointegrado',
            constraint=models.UniqueConstraint(fields=('provedor', 'transacao_externa_id'), name='uniq_confirmacao_provedor_transacao'),
        ),
        migrations.AddConstraint(
            model_name='confirmacaopagamentointegrado',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='confirmacao_integrada_valor_positivo'),
        ),
    ]
