# Generated by Django 6.0.6 on 2026-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_confirmacao_integracao_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='custo_unitario_no_momento',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
