# Generated by Django 6.0.6 on 2026-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_venda_cancelada_em_venda_cancelada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamentofilial',
            name='codigo_fiscal_tpag',
            field=models.CharField(blank=True, help_text='Se vazio, será usado o mapeamento fiscal padrão da forma de pagamento.', max_length=2, verbose_name='Código fiscal tPag'),
        ),
        migrations.AddField(
            model_name='formapagamentofilial',
            name='descricao_fiscal_xpag',
            field=models.CharField(blank=True, help_text='Obrigatória somente quando o código fiscal tPag for 99.', max_length=60, verbose_name='Descrição fiscal xPag'),
        ),
        migrations.AddField(
            model_name='pagamentovenda',
            name='valor_informado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='formapagamentofilial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('codigo_fiscal_tpag', '99'), models.Q(('descricao_fiscal_xpag', ''), _negated=True)), models.Q(models.Q(('codigo_fiscal_tpag', '99'), _negated=True), ('descricao_fiscal_xpag', '')), _connector='OR'), name='vendas_tpag_xpag_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='pagamentovenda',
            constraint=models.CheckConstraint(condition=models.Q(('valor_informado__isnull', True), ('valor_informado__gte', models.F('valor')), _connector='OR'), name='vendas_valor_informado_gte_aplicado'),
        ),
    ]
