# Generated by Django 6.0.6 on 2026-10-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('pdv', '0013_alter_terminalpdv_modo_integracao_tef_and_more'),
        ('vendas', '0017_formapagamentofilial_codigo_fiscal_tpag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(unique=True)),
                ('terminal_identificador', models.CharField(blank=True, max_length=120)),
                ('assinatura_requisicao', models.CharField(max_length=64)),
                ('assinatura_carrinho', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdv.caixa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.venda')),
            ],
        ),
    ]
