# Generated by Django 6.0.6 on 2026-07-01 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('canal', models.CharField(choices=[('LOJA_ONLINE', 'Loja online'), ('WHATSAPP', 'WhatsApp'), ('TELEFONE', 'Telefone'), ('MARKETPLACE', 'Marketplace parceiro')], default='LOJA_ONLINE', max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('RETIRADA', 'Retirada na loja'), ('ENTREGA', 'Entrega')], default='RETIRADA', max_length=20)),
                ('endereco_entrega', models.TextField(blank=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_SEPARACAO', 'Em separacao'), ('PRONTO', 'Pronto'), ('SAIU_ENTREGA', 'Saiu para entrega'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('estoque_reservado', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_online', to='clientes.cliente')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_online', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_online_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_online', to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='marketplace.pedidoonline')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('pedido', 'produto')},
            },
        ),
    ]
