# Generated by Django 6.0.6 on 2026-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidoonline',
            name='quantidade_separada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CARTAO', 'Cartao'), ('DINHEIRO', 'Dinheiro'), ('GATEWAY', 'Gateway/marketplace'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
