# Generated by Django 6.0.6 on 2026-07-01 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('marketplace', '0002_itempedidoonline_quantidade_separada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('token_prefixo', models.CharField(db_index=True, max_length=12)),
                ('token_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integracoes_marketplace', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integracoes_marketplace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='integracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='marketplace.integracaomarketplace'),
        ),
        migrations.AddConstraint(
            model_name='pedidoonline',
            constraint=models.UniqueConstraint(condition=models.Q(('integracao__isnull', False)), fields=('integracao', 'referencia_externa'), name='pedido_referencia_unica_por_integracao'),
        ),
    ]
