# Generated by Django 6.0.6 on 2026-07-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('marketplace', '0003_integracaomarketplace_pedidoonline_integracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoonline',
            name='distancia_entrega_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='regra_entrega_aplicada',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.CreateModel(
            name='PoliticaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raio_maximo_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_minimo_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frete_gratis_acima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bairros_atendidos', models.TextField(blank=True, help_text='Separe bairros ou setores por virgula.')),
                ('bairros_bloqueados', models.TextField(blank=True, help_text='Separe bairros ou setores por virgula.')),
                ('horarios_entrega', models.TextField(blank=True)),
                ('permite_retirada', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='politica_entrega', to='empresas.filial')),
            ],
            options={
                'ordering': ['filial__empresa__nome_fantasia', 'filial__nome'],
            },
        ),
        migrations.CreateModel(
            name='FaixaTaxaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_inicial_km', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('distancia_final_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='marketplace.politicaentrega')),
            ],
            options={
                'ordering': ['distancia_inicial_km'],
            },
        ),
    ]
