# Generated by Django 6.0.6 on 2026-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_pedidoonline_distancia_entrega_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoonline',
            name='documento_cliente',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='documento_cliente_tipo',
            field=models.CharField(choices=[('NAO_IDENTIFICADO', 'Nao identificado'), ('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('ESTRANGEIRO', 'Documento estrangeiro')], default='NAO_IDENTIFICADO', max_length=20),
        ),
    ]
