# Generated by Django 6.0.6 on 2026-07-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_integracaomarketplace_provedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoonline',
            name='referencia_pagamento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CARTAO', 'Cartao'), ('CARTAO_CREDITO_ENTREGA', 'Cartao de credito na entrega'), ('CARTAO_DEBITO_ENTREGA', 'Cartao de debito na entrega'), ('DINHEIRO', 'Dinheiro'), ('GATEWAY', 'Gateway/marketplace'), ('OUTRO', 'Outro')], max_length=40),
        ),
    ]
