# Generated by Django 6.0.6 on 2026-07-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_pagamento_cartao_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoonline',
            name='bairro_entrega',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
