# Generated by Django 6.0.6 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_pedidoonline_bairro_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaomarketplace',
            name='provedor',
            field=models.CharField(choices=[('PADRAO', 'Contrato padrão'), ('IFOOD', 'iFood'), ('RAPPI', 'Rappi'), ('MERCADO_LIVRE', 'Mercado Livre'), ('SITE_PROPRIO', 'Site proprio'), ('OUTRO', 'Outro parceiro')], default='PADRAO', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='documento_cliente_tipo',
            field=models.CharField(choices=[('NAO_IDENTIFICADO', 'Não identificado'), ('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('ESTRANGEIRO', 'Documento estrangeiro')], default='NAO_IDENTIFICADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_SEPARACAO', 'Em separação'), ('PRONTO', 'Pronto'), ('SAIU_ENTREGA', 'Saiu para entrega'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20),
        ),
    ]
