# Generated by Django 6.0.6 on 2026-07-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_integracaomarketplace_provedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaomarketplace',
            name='provedor',
            field=models.CharField(choices=[('PADRAO', 'Contrato padrão'), ('IFOOD', 'iFood'), ('RAPPI', 'Rappi'), ('MERCADO_LIVRE', 'Mercado Livre'), ('SITE_PROPRIO', 'Site próprio'), ('OUTRO', 'Outro parceiro')], default='PADRAO', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão'), ('CARTAO_CREDITO_ENTREGA', 'Cartão de crédito na entrega'), ('CARTAO_DEBITO_ENTREGA', 'Cartão de débito na entrega'), ('DINHEIRO', 'Dinheiro'), ('GATEWAY', 'Gateway/marketplace'), ('OUTRO', 'Outro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_SEPARACAO', 'Em separação'), ('PRONTO', 'Pronto'), ('SAIU_ENTREGA', 'Saiu para entrega'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='politicaentrega',
            name='bairros_atendidos',
            field=models.TextField(blank=True, help_text='Separe bairros ou setores por vírgula.'),
        ),
        migrations.AlterField(
            model_name='politicaentrega',
            name='bairros_bloqueados',
            field=models.TextField(blank=True, help_text='Separe bairros ou setores por vírgula.'),
        ),
    ]
