# Generated by Django 6.0.6 on 2026-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_integracaomarketplace_provedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_bairro',
            field=models.CharField(blank=True, max_length=60, verbose_name='Bairro fiscal'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP fiscal'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_codigo_municipio_ibge',
            field=models.CharField(blank=True, max_length=7, verbose_name='Código IBGE do município'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_complemento',
            field=models.CharField(blank=True, max_length=60, verbose_name='Complemento fiscal'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_indicador_ie',
            field=models.CharField(blank=True, choices=[('1', 'Contribuinte de ICMS'), ('2', 'Contribuinte isento de inscrição'), ('9', 'Não contribuinte')], default='', max_length=1, verbose_name='Indicador de IE'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_logradouro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Logradouro fiscal'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_municipio',
            field=models.CharField(blank=True, max_length=60, verbose_name='Município fiscal'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_numero',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número fiscal'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='destinatario_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF fiscal'),
        ),
    ]
