# Generated by Django 6.0.6 on 2026-10-05 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_pedidoonline_destinatario_bairro_and_more'),
        ('pdv', '0013_alter_terminalpdv_modo_integracao_tef_and_more'),
        ('vendas', '0017_formapagamentofilial_codigo_fiscal_tpag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidoonline',
            name='custo_unitario_no_momento',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PagamentoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_informado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('RECUSADO', 'Recusado'), ('ESTORNO_PENDENTE', 'Estorno pendente'), ('ESTORNADO', 'Estornado')], default='CONFIRMADO', max_length=30)),
                ('origem_recebimento', models.CharField(choices=[('CAIXA_PDV', 'Caixa PDV'), ('ENTREGA', 'Entrega')], max_length=20)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('transacao_externa_id', models.CharField(blank=True, max_length=120)),
                ('nsu', models.CharField(blank=True, max_length=60)),
                ('codigo_autorizacao', models.CharField(blank=True, max_length=128)),
                ('tipo_integracao', models.CharField(blank=True, max_length=1)),
                ('cnpj_instituicao_pagamento', models.CharField(blank=True, max_length=14)),
                ('bandeira_cartao', models.CharField(blank=True, max_length=2)),
                ('cnpj_beneficiario_pagamento', models.CharField(blank=True, max_length=14)),
                ('identificador_terminal_pagamento', models.CharField(blank=True, max_length=40)),
                ('mensagem_processadora', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=80, unique=True)),
                ('status_acerto', models.CharField(choices=[('NAO_APLICA', 'Não se aplica'), ('PENDENTE', 'Pendente'), ('ACERTADO', 'Acertado')], default='NAO_APLICA', max_length=12)),
                ('acertado_em', models.DateTimeField(blank=True, null=True)),
                ('caixa_acerto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acertos_entrega', to='pdv.caixa')),
                ('caixa_recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_pedido', to='pdv.caixa')),
                ('confirmacao_integracao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_pedido', to='vendas.confirmacaopagamentointegrado')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='marketplace.pedidoonline')),
                ('usuario_acerto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acertos_entrega_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_pedido_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recebido_em', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pedido_pagamento_valor_positivo'), models.CheckConstraint(condition=models.Q(('valor_informado__gte', models.F('valor'))), name='pedido_pagamento_informado_gte_aplicado'), models.CheckConstraint(condition=models.Q(models.Q(('caixa_recebimento__isnull', False), ('origem_recebimento', 'CAIXA_PDV')), models.Q(('caixa_recebimento__isnull', True), ('origem_recebimento', 'ENTREGA')), _connector='OR'), name='pedido_pagamento_caixa_por_origem')],
            },
        ),
    ]
