# Generated by Django 6.0.6 on 2026-10-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_itempedidoonline_custo_unitario_no_momento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoonline',
            name='canal',
            field=models.CharField(choices=[('PDV', 'PDV'), ('LOJA_ONLINE', 'Loja online'), ('WHATSAPP', 'WhatsApp'), ('TELEFONE', 'Telefone'), ('MARKETPLACE', 'Marketplace parceiro')], default='LOJA_ONLINE', max_length=20),
        ),
    ]
