# Generated by Django 6.0.6 on 2026-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_atribuir_empresa_clientes_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, max_length=7, verbose_name='Código IBGE do município'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indicador_ie',
            field=models.CharField(blank=True, choices=[('1', 'Contribuinte de ICMS'), ('2', 'Contribuinte isento de inscrição'), ('9', 'Não contribuinte')], default='', max_length=1, verbose_name='Indicador de IE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(blank=True, max_length=60, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
