# Generated by Django 6.0.6 on 2026-07-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('compras', '0001_initial'),
        ('empresas', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('vendas', '0003_devolucaovenda_itemdevolucaovenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('PAGAR', 'Conta a pagar'), ('RECEBER', 'Conta a receber')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGAR', 'Conta a pagar'), ('RECEBER', 'Conta a receber')], max_length=20)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='financeiro.categoriafinanceira')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='clientes.cliente')),
                ('entrada_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='compras.entradacompra')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='empresas.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='fornecedores.fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='vendas.venda')),
            ],
            options={
                'ordering': ['status', 'vencimento', 'descricao'],
            },
        ),
    ]
