# Generated by Django 6.0.6 on 2026-07-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_lancamentofinanceiro_estorno_de'),
        ('vendas', '0005_pagamentovenda_estorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='pagamento_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='vendas.pagamentovenda'),
        ),
    ]
