# Generated by Django 6.0.6 on 2026-07-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_lancamentofinanceiro_pagamento_venda'),
        ('pdv', '0005_terminalpdv_chave_api_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='sangria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='pdv.sangria'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='suprimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='pdv.suprimento'),
        ),
    ]
