# Generated by Django 6.0.6 on 2026-07-27 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_lancamentofinanceiro_sangria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoLancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conciliacao', models.DateField(default=django.utils.timezone.localdate)),
                ('referencia_externa', models.CharField(max_length=120)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lancamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacao_bancaria', to='financeiro.lancamentofinanceiro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_financeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_conciliacao', '-criado_em'],
            },
        ),
    ]
