# Generated by Django 6.0.6 on 2026-07-29 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_alter_eventoentradasincronizacao_status_and_more'),
        ('financeiro', '0007_conciliacaolancamentofinanceiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportacaoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('contrato', models.CharField(default='financial_accounting_package_v1', max_length=80)),
                ('chave_idempotencia', models.CharField(max_length=64, unique=True)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('provedor', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('REJEITADO', 'Rejeitado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('protocolo', models.CharField(blank=True, max_length=120)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exportacoes_contabeis', to='empresas.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exportacoes_contabeis', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exportacoes_contabeis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'data_inicio', 'data_fim'], name='fin_exp_empresa_periodo_idx')],
            },
        ),
    ]
