# Generated by Django 6.0.6 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_categoriafinanceira_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contamovimentofinanceiro',
            name='tipo',
            field=models.CharField(choices=[('CAIXA', 'Caixa físico'), ('BANCO', 'Conta bancária'), ('PIX', 'Conta PIX'), ('OUTRA', 'Outra')], max_length=20),
        ),
    ]
