# Generated by Django 6.0.6 on 2026-08-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_alter_empresa_modo_implantacao'),
        ('financeiro', '0010_alter_contamovimentofinanceiro_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Centro de custo',
                'verbose_name_plural': 'Centros de custo',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='financeiro.centrocusto', verbose_name='Centro de custo'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.centrocusto', verbose_name='Centro de custo'),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='financeiro_centro_codigo_unico_empresa'),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='financeiro_centro_nome_unico_empresa'),
        ),
    ]
