# Generated by Django 6.0.6 on 2026-08-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_alter_empresa_modo_implantacao'),
        ('financeiro', '0011_centrocusto_contafinanceira_centro_custo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=160)),
                ('natureza', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PATRIMONIO_LIQUIDO', 'Patrim?nio l?quido'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('COMPENSACAO', 'Compensa??o')], max_length=30)),
                ('tipo', models.CharField(choices=[('SINTETICA', 'Sint?tica'), ('ANALITICA', 'Anal?tica')], default='ANALITICA', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontas', to='financeiro.contacontabil', verbose_name='Conta superior')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plano_contas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conta cont?bil',
                'verbose_name_plural': 'Plano de contas',
                'ordering': ['empresa', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='categoriafinanceira',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_financeiras', to='financeiro.contacontabil', verbose_name='Conta cont?bil'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contacontabil', verbose_name='Conta cont?bil'),
        ),
        migrations.AddConstraint(
            model_name='contacontabil',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='financeiro_conta_contabil_codigo_empresa'),
        ),
    ]
