# Generated by Django 6.0.6 on 2026-08-12 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_criar_filiais_matriz_ausentes'),
        ('financeiro', '0012_contacontabil_categoriafinanceira_conta_contabil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveIntegracaoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('valida_ate', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('ultima_utilizacao_em', models.DateTimeField(blank=True, null=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaves_integracao_contabil_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaves_integracao_contabil', to='empresas.empresa')),
            ],
            options={
                'ordering': ['empresa__nome_fantasia', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nome'), name='financeiro_chave_contabil_empresa_nome')],
            },
        ),
    ]
