# Generated by Django 6.0.6 on 2026-08-17 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_chaveintegracaocontabil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoExtratoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('arquivo_sha256', models.CharField(max_length=64)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('conciliadas_automaticamente', models.PositiveIntegerField(default=0)),
                ('pendentes', models.PositiveIntegerField(default=0)),
                ('ambiguas', models.PositiveIntegerField(default=0)),
                ('duplicadas', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato', to='financeiro.contamovimentofinanceiro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato_financeiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemExtratoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linha', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descricao', models.CharField(max_length=255)),
                ('referencia_externa', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AMBIGUO', 'Ambíguo'), ('CONCILIADO', 'Conciliado')], default='PENDENTE', max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_extrato', to='financeiro.contamovimentofinanceiro')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='financeiro.importacaoextratofinanceiro')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_extrato', to='financeiro.lancamentofinanceiro')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='importacaoextratofinanceiro',
            constraint=models.UniqueConstraint(fields=('conta', 'arquivo_sha256'), name='financeiro_extrato_arquivo_unico'),
        ),
        migrations.AddIndex(
            model_name='itemextratofinanceiro',
            index=models.Index(fields=['conta', 'status', 'data'], name='fin_ext_conta_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemextratofinanceiro',
            constraint=models.UniqueConstraint(fields=('conta', 'referencia_externa'), name='financeiro_extrato_referencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='itemextratofinanceiro',
            constraint=models.UniqueConstraint(fields=('importacao', 'numero_linha'), name='financeiro_extrato_linha_unica'),
        ),
    ]
