# Generated by Django 6.0.6 on 2026-08-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('financeiro', '0014_importacaoextratofinanceiro_itemextratofinanceiro_and_more'),
        ('vendas', '0012_alter_venda_documento_consumidor_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraLiquidacaoEletronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_dias', models.PositiveSmallIntegerField(default=1)),
                ('taxa_percentual', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_liquidacao_eletronica', to='empresas.filial')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_liquidacao_eletronica', to='vendas.formapagamento')),
            ],
            options={
                'ordering': ['filial__nome', 'forma_pagamento__nome'],
            },
        ),
        migrations.CreateModel(
            name='RecebivelEletronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('LIQUIDADO', 'Liquidado'), ('DIVERGENTE', 'Divergente'), ('CHARGEBACK', 'Chargeback')], default='PENDENTE', max_length=20)),
                ('data_venda', models.DateField()),
                ('data_prevista', models.DateField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taxa_prevista', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_liquido_previsto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_liquidacao', models.DateField(blank=True, null=True)),
                ('valor_liquidado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('referencia_liquidacao', models.CharField(blank=True, max_length=120)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recebivel_eletronico', to='vendas.pagamentovenda')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='financeiro.regraliquidacaoeletronica')),
            ],
            options={
                'ordering': ['data_prevista', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='regraliquidacaoeletronica',
            constraint=models.UniqueConstraint(fields=('filial', 'forma_pagamento'), name='financeiro_regra_liquidacao_unica'),
        ),
        migrations.AddIndex(
            model_name='recebiveleletronico',
            index=models.Index(fields=['status', 'data_prevista'], name='fin_receb_status_data_idx'),
        ),
    ]
