# Generated by Django 6.0.6 on 2026-08-17 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_regraliquidacaoeletronica_recebiveleletronico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebiveleletronico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('LIQUIDADO', 'Liquidado'), ('ANTECIPADO', 'Antecipado'), ('DIVERGENTE', 'Divergente'), ('CHARGEBACK', 'Chargeback')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='MovimentoRecebivelEletronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIQUIDACAO', 'Liquidação'), ('ANTECIPACAO', 'Antecipação'), ('CHARGEBACK', 'Chargeback')], max_length=20)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(max_length=120)),
                ('automatico', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_extrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_recebiveis', to='financeiro.itemextratofinanceiro')),
                ('recebivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.recebiveleletronico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_recebiveis_eletronicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['tipo', 'data'], name='fin_mov_receb_tipo_data_idx')],
                'constraints': [models.UniqueConstraint(fields=('recebivel', 'item_extrato', 'tipo'), name='financeiro_mov_recebivel_item_tipo_unico'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='financeiro_mov_recebivel_valor_positivo')],
            },
        ),
    ]
