# Generated by Django 6.0.6 on 2026-08-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_alter_recebiveleletronico_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemextratofinanceiro',
            name='financeiro_extrato_referencia_unica',
        ),
        migrations.AddConstraint(
            model_name='itemextratofinanceiro',
            constraint=models.UniqueConstraint(fields=('conta', 'referencia_externa', 'tipo', 'data'), name='financeiro_extrato_movimento_unico'),
        ),
    ]
