# Generated by Django 6.0.6 on 2026-08-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_remove_itemextratofinanceiro_financeiro_extrato_referencia_unica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemextratofinanceiro',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AMBIGUO', 'Ambíguo'), ('PARCIAL', 'Parcialmente alocado'), ('CONCILIADO', 'Conciliado')], default='PENDENTE', max_length=20),
        ),
    ]
