# Generated by Django 6.0.6 on 2026-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_alter_itemextratofinanceiro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoextratofinanceiro',
            name='adaptador_codigo',
            field=models.CharField(default='CSV_GENERICO', max_length=40),
        ),
        migrations.AddField(
            model_name='importacaoextratofinanceiro',
            name='adaptador_contrato',
            field=models.CharField(default='financial_statement_adapter_v1', max_length=80),
        ),
        migrations.AddField(
            model_name='importacaoextratofinanceiro',
            name='adaptador_nome',
            field=models.CharField(default='CSV genérico do ERP', max_length=120),
        ),
    ]
