# Generated by Django 6.0.6 on 2026-08-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_importacaoextratofinanceiro_adaptador_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacontabil',
            options={'ordering': ['empresa', 'codigo'], 'verbose_name': 'Conta contábil', 'verbose_name_plural': 'Plano de contas'},
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_financeiras', to='financeiro.contacontabil', verbose_name='Conta contábil'),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='natureza',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PATRIMONIO_LIQUIDO', 'Patrimônio líquido'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('COMPENSACAO', 'Compensação')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='tipo',
            field=models.CharField(choices=[('SINTETICA', 'Sintética'), ('ANALITICA', 'Analítica')], default='ANALITICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contacontabil', verbose_name='Conta contábil'),
        ),
    ]
