# Generated by Django 6.0.6 on 2026-08-31 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('financeiro', '0020_alter_contacontabil_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoIntegracaoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('software_contabil', models.CharField(blank=True, max_length=160)),
                ('formato_entrega', models.CharField(choices=[('PACOTE_ZIP_V2', 'Pacote mensal ZIP v2'), ('API_JSON_V1', 'API mensal JSON v1'), ('ADAPTADOR_SERVIDOR_V1', 'Adaptador do servidor v1')], max_length=32)),
                ('contrato_tecnico', models.CharField(editable=False, max_length=80)),
                ('responsavel_efd_icms_ipi', models.CharField(choices=[('NAO_DEFINIDO', 'Ainda não definido'), ('ESCRITORIO_CONTABIL', 'Escritório contábil'), ('SOFTWARE_CONTABIL', 'Software contábil externo'), ('OUTRO_RESPONSAVEL', 'Outro responsável externo')], default='NAO_DEFINIDO', max_length=32)),
                ('responsavel_efd_nome', models.CharField(blank=True, max_length=160)),
                ('aceite_referencia', models.CharField(blank=True, help_text='Referência interna do aceite do contador, sem anexar credenciais ou segredos.', max_length=160)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('VALIDADO', 'Validado com o contador')], default='RASCUNHO', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_integracao_contabil_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_integracao_contabil', to='empresas.empresa')),
            ],
            options={
                'ordering': ['empresa__nome_fantasia', '-versao'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'versao'), name='financeiro_contrato_contabil_empresa_versao_uniq')],
            },
        ),
    ]
