# Generated by Django 6.0.6 on 2026-08-31 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('financeiro', '0021_contratointegracaocontabil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AceiteAmostraContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('pacote_sha256', models.CharField(max_length=64)),
                ('relatorio_validacao', models.JSONField()),
                ('referencia_aceite', models.CharField(max_length=160)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato_integracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_amostra', to='financeiro.contratointegracaocontabil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_amostra_contabil', to='empresas.empresa')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_amostra_contabil_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-competencia', '-registrado_em'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'competencia', 'pacote_sha256'), name='financeiro_aceite_amostra_empresa_comp_hash_uniq')],
            },
        ),
    ]
