# Generated by Django 6.0.6 on 2026-09-18 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_faturanfeentrada_duplicatanfeentrada'),
        ('financeiro', '0023_conta_baixa_integral_coerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contafinanceira',
            name='duplicata_nfe_entrada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta_financeira', to='compras.duplicatanfeentrada'),
        ),
    ]
