# Generated by Django 6.0.6 on 2026-09-21 11:47

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def validar_origens_legadas(apps, schema_editor):
    ContaFinanceira = apps.get_model("financeiro", "ContaFinanceira")
    problemas = {}

    def ids(nome, queryset):
        encontrados = list(queryset.order_by("pk").values_list("pk", flat=True)[:50])
        if encontrados:
            problemas[nome] = encontrados

    ids(
        "venda_e_compra_simultaneas",
        ContaFinanceira.objects.filter(venda__isnull=False, entrada_compra__isnull=False),
    )
    ids(
        "duplicata_sem_compra",
        ContaFinanceira.objects.filter(
            duplicata_nfe_entrada__isnull=False,
            entrada_compra__isnull=True,
        ),
    )
    ids(
        "venda_sem_tipo_receber",
        ContaFinanceira.objects.filter(venda__isnull=False).exclude(tipo="RECEBER"),
    )
    ids(
        "compra_sem_tipo_pagar",
        ContaFinanceira.objects.filter(entrada_compra__isnull=False).exclude(tipo="PAGAR"),
    )

    vendas_duplicadas = list(
        ContaFinanceira.objects.filter(venda__isnull=False)
        .values("venda_id")
        .annotate(quantidade=Count("id"))
        .filter(quantidade__gt=1)
        .order_by("venda_id")[:50]
    )
    if vendas_duplicadas:
        problemas["vendas_com_multiplas_contas"] = vendas_duplicadas

    compras_duplicadas = list(
        ContaFinanceira.objects.filter(
            entrada_compra__isnull=False,
            duplicata_nfe_entrada__isnull=True,
        )
        .values("entrada_compra_id")
        .annotate(quantidade=Count("id"))
        .filter(quantidade__gt=1)
        .order_by("entrada_compra_id")[:50]
    )
    if compras_duplicadas:
        problemas["compras_com_multiplas_contas_sem_duplicata"] = compras_duplicadas

    if problemas:
        detalhes = "; ".join(f"{nome}={valores}" for nome, valores in problemas.items())
        raise RuntimeError(
            "Contas financeiras legadas incompatíveis com as constraints de origem. "
            "Corrija manualmente antes de reaplicar a migration: " + detalhes
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_bairro_cliente_cep_and_more'),
        ('compras', '0012_faturanfeentrada_duplicatanfeentrada'),
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('financeiro', '0024_contafinanceira_duplicata_nfe_entrada'),
        ('fornecedores', '0004_fornecedor_bairro_fornecedor_cep_and_more'),
        ('vendas', '0012_alter_venda_documento_consumidor_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validar_origens_legadas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('venda__isnull', True), ('entrada_compra__isnull', True), _connector='OR'), name='fin_conta_origem_exclusiva'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('duplicata_nfe_entrada__isnull', True), ('entrada_compra__isnull', False), _connector='OR'), name='fin_conta_duplicata_exige_compra'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('venda__isnull', True), ('tipo', 'RECEBER'), _connector='OR'), name='fin_conta_venda_receber'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('entrada_compra__isnull', True), ('tipo', 'PAGAR'), _connector='OR'), name='fin_conta_compra_pagar'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('venda__isnull', False)), fields=('venda',), name='fin_conta_venda_unica'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('entrada_compra__isnull', False), ('duplicata_nfe_entrada__isnull', True)), fields=('entrada_compra',), name='fin_conta_compra_unica_sem_dup'),
        ),
    ]
