# Generated by Django 6.0.6 on 2026-09-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_protege_origens_conta_financeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanceira',
            name='grupo_dre',
            field=models.CharField(choices=[('NAO_CLASSIFICADO', 'Não classificado'), ('DESPESA_OPERACIONAL', 'Despesa operacional'), ('DESPESA_FINANCEIRA', 'Despesa financeira'), ('TRIBUTO_RESULTADO', 'Tributo sobre resultado'), ('OUTRA_RECEITA', 'Outra receita'), ('OUTRA_DESPESA', 'Outra despesa')], default='NAO_CLASSIFICADO', help_text='Classificação gerencial utilizada na DRE; não substitui conta contábil nem classificação do contador.', max_length=30),
        ),
    ]
