# Generated by Django 6.0.6 on 2026-09-28 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('financeiro', '0026_categoriafinanceira_grupo_dre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaFinanceiroContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Primeiro dia do mês da competência.')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias_financeiro_contabeis', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-competencia', 'empresa__nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoMensalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('filiais_snapshot', models.JSONField()),
                ('dre_snapshot', models.JSONField()),
                ('financeiro_snapshot', models.JSONField()),
                ('contas_snapshot', models.JSONField()),
                ('recebiveis_snapshot', models.JSONField()),
                ('inventario_snapshot', models.JSONField()),
                ('fiscal_snapshot', models.JSONField()),
                ('diagnostico_snapshot', models.JSONField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('com_ressalvas', models.BooleanField(default=False)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='financeiro.competenciafinanceirocontabil')),
                ('fechado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_mensais_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-competencia__competencia', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='EventoCompetenciaFinanceiroContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FECHAMENTO', 'Fechamento'), ('REABERTURA', 'Reabertura')], max_length=16)),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='financeiro.competenciafinanceirocontabil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_competencia_financeiro_contabil', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_competencia', to='financeiro.fechamentomensalsnapshot')),
            ],
            options={
                'ordering': ['-ocorrido_em', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='competenciafinanceirocontabil',
            name='fechamento_vigente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias_em_que_e_vigente', to='financeiro.fechamentomensalsnapshot'),
        ),
        migrations.AddConstraint(
            model_name='fechamentomensalsnapshot',
            constraint=models.UniqueConstraint(fields=('competencia', 'versao'), name='fin_fechamento_competencia_versao_uniq'),
        ),
        migrations.AddConstraint(
            model_name='competenciafinanceirocontabil',
            constraint=models.UniqueConstraint(fields=('empresa', 'competencia'), name='fin_competencia_empresa_mes_uniq'),
        ),
    ]
