# Generated by Django 6.0.6 on 2026-09-29 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0027_competenciafinanceirocontabil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contafinanceira',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='motivo_cancelamento',
            field=models.TextField(blank=True),
        ),
    ]
