# Generated by Django 6.0.6 on 2026-10-05 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0028_contafinanceira_cancelada_em_and_more'),
        ('marketplace', '0012_itempedidoonline_custo_unitario_no_momento_and_more'),
        ('pdv', '0013_alter_terminalpdv_modo_integracao_tef_and_more'),
        ('vendas', '0017_formapagamentofilial_codigo_fiscal_tpag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='pagamento_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='marketplace.pagamentopedido'),
        ),
        migrations.AddField(
            model_name='recebiveleletronico',
            name='pagamento_pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebivel_eletronico', to='marketplace.pagamentopedido'),
        ),
        migrations.AlterField(
            model_name='recebiveleletronico',
            name='pagamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebivel_eletronico', to='vendas.pagamentovenda'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('pagamento_venda__isnull', True), ('pagamento_pedido__isnull', True), _connector='OR'), name='lancamento_uma_origem_pagamento'),
        ),
        migrations.AddConstraint(
            model_name='recebiveleletronico',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pagamento__isnull', False), ('pagamento_pedido__isnull', True)), models.Q(('pagamento__isnull', True), ('pagamento_pedido__isnull', False)), _connector='OR'), name='recebivel_exatamente_uma_origem_pagamento'),
        ),
    ]
