# Generated by Django 6.0.6 on 2026-06-25 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida'), ('AJUSTE', 'Ajuste'), ('VENDA', 'Venda'), ('DEVOLUCAO', 'Devolucao'), ('RESERVA', 'Reserva'), ('LIBERACAO_RESERVA', 'Liberacao de reserva')], max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='empresas.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='empresas.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='produtos.produto')),
            ],
            options={
                'ordering': ['produto__nome', 'filial__nome'],
                'unique_together': {('produto', 'filial')},
            },
        ),
    ]
