# Generated by Django 6.0.6 on 2026-06-29 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('estoque', '0002_inventarioestoque_iteminventarioestoque'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida'), ('AJUSTE', 'Ajuste'), ('VENDA', 'Venda'), ('DEVOLUCAO', 'Devolucao'), ('PERDA', 'Perda'), ('RESERVA', 'Reserva'), ('LIBERACAO_RESERVA', 'Liberacao de reserva')], max_length=30),
        ),
        migrations.CreateModel(
            name='PerdaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENCIMENTO', 'Vencimento'), ('AVARIA', 'Avaria'), ('QUEBRA', 'Quebra'), ('EXTRAVIO_FURTO', 'Extravio/furto'), ('CONSUMO_INTERNO', 'Consumo interno'), ('DEVOLUCAO_NAO_REAPROVEITAVEL', 'Devolucao nao reaproveitavel'), ('OUTROS', 'Outros')], max_length=40)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motivo', models.CharField(max_length=255)),
                ('custo_unitario_no_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda_no_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_custo_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_venda_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perdas_estoque', to='empresas.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perdas', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perdas_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
