# Generated by Django 6.0.6 on 2026-07-09 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_empresa_logo'),
        ('estoque', '0003_alter_movimentacaoestoque_tipo_perdaestoque'),
        ('produtos', '0004_alter_produto_imagem_alter_produtoimagem_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida'), ('AJUSTE', 'Ajuste'), ('VENDA', 'Venda'), ('DEVOLUCAO', 'Devolucao'), ('PERDA', 'Perda'), ('RESERVA', 'Reserva'), ('LIBERACAO_RESERVA', 'Liberacao de reserva'), ('DESMEMBRAMENTO', 'Desmembramento')], max_length=30),
        ),
        migrations.CreateModel(
            name='DesmembramentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_origem', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_total_origem', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('SIMPLES', 'Simples / unitizacao'), ('CAIXA_FARDO', 'Caixa / fardo'), ('ACOUGUE', 'Acougue por rendimento'), ('PRODUCAO', 'Producao interna'), ('KIT', 'Kit / composicao')], default='SIMPLES', max_length=30)),
                ('metodo_custo', models.CharField(choices=[('QUANTIDADE', 'Proporcional por quantidade'), ('PESO', 'Proporcional por peso'), ('MANUAL', 'Custo manual autorizado')], default='QUANTIDADE', max_length=20)),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desmembramentos_produto', to='empresas.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desmembramentos_produto', to='empresas.filial')),
                ('produto_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desmembramentos_origem', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desmembramentos_produto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemDesmembramentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_gerada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidade', models.CharField(max_length=3)),
                ('custo_unitario_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual_rendimento', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tipo_saida', models.CharField(choices=[('VENDAVEL', 'Produto vendavel'), ('PERDA', 'Perda / descarte'), ('SUBPRODUTO', 'Subproduto')], default='VENDAVEL', max_length=20)),
                ('desmembramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.desmembramentoproduto')),
                ('produto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desmembramentos_destino', to='produtos.produto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
