# Generated by Django 6.0.6 on 2026-07-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_empresa_logo'),
        ('estoque', '0004_alter_movimentacaoestoque_tipo_desmembramentoproduto_and_more'),
        ('produtos', '0004_alter_produto_imagem_alter_produtoimagem_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaDesmembramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_origem', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('quantidade_destino', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tipo', models.CharField(choices=[('SIMPLES', 'Simples / unitizacao'), ('CAIXA_FARDO', 'Caixa / fardo'), ('ACOUGUE', 'Acougue por rendimento'), ('PRODUCAO', 'Producao interna'), ('KIT', 'Kit / composicao')], default='SIMPLES', max_length=30)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas_desmembramento', to='empresas.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas_desmembramento', to='empresas.filial')),
                ('produto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas_desmembramento_destino', to='produtos.produto')),
                ('produto_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas_desmembramento_origem', to='produtos.produto')),
            ],
            options={
                'ordering': ['produto_origem__nome', 'produto_destino__nome'],
            },
        ),
    ]
