# Generated by Django 6.0.6 on 2026-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_receitadesmembramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitadesmembramento',
            name='tipo_saida',
            field=models.CharField(choices=[('VENDAVEL', 'Produto vendavel'), ('PERDA', 'Perda / descarte'), ('SUBPRODUTO', 'Subproduto')], default='VENDAVEL', max_length=20),
        ),
    ]
