# Generated by Django 6.0.6 on 2026-07-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_receitadesmembramento_tipo_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdesmembramentoproduto',
            name='lote',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='itemdesmembramentoproduto',
            name='percentual_rendimento_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='itemdesmembramentoproduto',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
