# Generated by Django 6.0.6 on 2026-07-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_itemdesmembramentoproduto_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdaestoque',
            name='desmembramento_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perdas_geradas', to='estoque.itemdesmembramentoproduto'),
        ),
    ]
