# Generated by Django 6.0.6 on 2026-07-10 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_empresa_logo'),
        ('estoque', '0008_perdaestoque_desmembramento_item'),
        ('produtos', '0004_alter_produto_imagem_alter_produtoimagem_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_final', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('tipo', models.CharField(choices=[('SIMPLES', 'Simples / unitizacao'), ('CAIXA_FARDO', 'Caixa / fardo'), ('ACOUGUE', 'Acougue por rendimento'), ('PRODUCAO', 'Producao interna'), ('KIT', 'Kit / composicao')], default='KIT', max_length=30)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes_produto', to='empresas.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='composicoes_produto', to='empresas.filial')),
                ('produto_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes_final', to='produtos.produto')),
            ],
            options={
                'ordering': ['produto_final__nome'],
            },
        ),
        migrations.CreateModel(
            name='ProducaoComposicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_final', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='estoque.composicaoproduto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes_composicao', to='empresas.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes_composicao', to='empresas.filial')),
                ('produto_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes_composicao', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes_composicao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemProducaoComposicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_consumida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produto_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_producao_composicao', to='produtos.produto')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.producaocomposicaoproduto')),
            ],
            options={
                'ordering': ['produto_componente__nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemComposicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.composicaoproduto')),
                ('produto_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes_componente', to='produtos.produto')),
            ],
            options={
                'ordering': ['produto_componente__nome'],
                'unique_together': {('composicao', 'produto_componente')},
            },
        ),
    ]
