# Generated by Django 6.0.6 on 2026-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_composicaoproduto_producaocomposicaoproduto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaoproduto',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Simples / unitizacao'), ('CAIXA_FARDO', 'Caixa / fardo'), ('HORTIFRUTI', 'Hortifruti reembalado'), ('ACOUGUE', 'Acougue por rendimento'), ('PRODUCAO', 'Producao interna'), ('KIT', 'Kit / composicao')], default='KIT', max_length=30),
        ),
        migrations.AlterField(
            model_name='desmembramentoproduto',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Simples / unitizacao'), ('CAIXA_FARDO', 'Caixa / fardo'), ('HORTIFRUTI', 'Hortifruti reembalado'), ('ACOUGUE', 'Acougue por rendimento'), ('PRODUCAO', 'Producao interna'), ('KIT', 'Kit / composicao')], default='SIMPLES', max_length=30),
        ),
        migrations.AlterField(
            model_name='receitadesmembramento',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Simples / unitizacao'), ('CAIXA_FARDO', 'Caixa / fardo'), ('HORTIFRUTI', 'Hortifruti reembalado'), ('ACOUGUE', 'Acougue por rendimento'), ('PRODUCAO', 'Producao interna'), ('KIT', 'Kit / composicao')], default='SIMPLES', max_length=30),
        ),
    ]
