# Generated by Django 6.0.6 on 2026-07-23 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_empresa_logo'),
        ('estoque', '0010_alter_composicaoproduto_tipo_and_more'),
        ('produtos', '0004_alter_produto_imagem_alter_produtoimagem_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducaoComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_planejada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('data_programada', models.DateField()),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('PRODUZIDA', 'Produzida'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='estoque.composicaoproduto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao_composicao', to='empresas.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao_composicao', to='empresas.filial')),
                ('producao_gerada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_origem', to='estoque.producaocomposicaoproduto')),
                ('produto_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao_composicao', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao_composicao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_programada', 'produto_final__nome'],
            },
        ),
    ]
