# Generated by Django 6.0.6 on 2026-07-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_ordemproducaocomposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducaocomposicao',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20),
        ),
    ]
