# Generated by Django 6.0.6 on 2026-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_ordemproducaocomposicao_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducaocomposicao',
            name='setor_responsavel',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
