# Generated by Django 6.0.6 on 2026-07-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_ordemproducaocomposicao_setor_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducaocomposicao',
            name='etapa_operacional',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('SEPARACAO', 'Separação'), ('PRODUCAO', 'Produção'), ('CONFERENCIA', 'Conferência')], default='AGUARDANDO', max_length=20),
        ),
    ]
