# Generated by Django 6.0.6 on 2026-07-23 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_ordemproducaocomposicao_etapa_operacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducaocomposicao',
            name='responsavel_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao_operacionais', to=settings.AUTH_USER_MODEL),
        ),
    ]
