# Generated by Django 6.0.6 on 2026-07-23 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_ordemproducaocomposicao_responsavel_operacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEtapaOrdemProducaoComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(blank=True, choices=[('AGUARDANDO', 'Aguardando'), ('SEPARACAO', 'Separação'), ('PRODUCAO', 'Produção'), ('CONFERENCIA', 'Conferência')], max_length=20)),
                ('etapa_nova', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('SEPARACAO', 'Separação'), ('PRODUCAO', 'Produção'), ('CONFERENCIA', 'Conferência')], max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='estoque.ordemproducaocomposicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_etapa_ordem_producao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
