# Generated by Django 6.0.6 on 2026-07-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_empresa_logo'),
        ('estoque', '0016_historicoetapaordemproducaocomposicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSLASetorProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=80)),
                ('meta_minutos', models.PositiveIntegerField(default=240)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slas_setor_producao', to='empresas.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slas_setor_producao', to='empresas.filial')),
            ],
            options={
                'ordering': ['empresa__nome_fantasia', 'filial__nome', 'setor'],
                'unique_together': {('empresa', 'filial', 'setor')},
            },
        ),
    ]
