# Generated by Django 6.0.6 on 2026-07-23 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_configuracaoslasetorproducao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSLAOrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=30)),
                ('mensagem', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visualizado_em', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_sla', to='estoque.ordemproducaocomposicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_sla_producao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('ordem', 'usuario', 'papel')},
            },
        ),
    ]
