# Generated by Django 6.0.6 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_lote_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaoproduto',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Simples / unitização'), ('CAIXA_FARDO', 'Caixa / fardo'), ('HORTIFRUTI', 'Hortifruti reembalado'), ('ACOUGUE', 'Açougue por rendimento'), ('PRODUCAO', 'Produção interna'), ('KIT', 'Kit / composição')], default='KIT', max_length=30),
        ),
        migrations.AlterField(
            model_name='desmembramentoproduto',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Simples / unitização'), ('CAIXA_FARDO', 'Caixa / fardo'), ('HORTIFRUTI', 'Hortifruti reembalado'), ('ACOUGUE', 'Açougue por rendimento'), ('PRODUCAO', 'Produção interna'), ('KIT', 'Kit / composição')], default='SIMPLES', max_length=30),
        ),
        migrations.AlterField(
            model_name='perdaestoque',
            name='tipo',
            field=models.CharField(choices=[('VENCIMENTO', 'Vencimento'), ('AVARIA', 'Avaria'), ('QUEBRA', 'Quebra'), ('EXTRAVIO_FURTO', 'Extravio/furto'), ('CONSUMO_INTERNO', 'Consumo interno'), ('DEVOLUCAO_NAO_REAPROVEITAVEL', 'Devolução não reaproveitável'), ('OUTROS', 'Outros')], max_length=40),
        ),
        migrations.AlterField(
            model_name='receitadesmembramento',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Simples / unitização'), ('CAIXA_FARDO', 'Caixa / fardo'), ('HORTIFRUTI', 'Hortifruti reembalado'), ('ACOUGUE', 'Açougue por rendimento'), ('PRODUCAO', 'Produção interna'), ('KIT', 'Kit / composição')], default='SIMPLES', max_length=30),
        ),
    ]
