# Generated by Django 6.0.6 on 2026-07-31 12:17

from django.db import migrations, models


def preencher_custo_medio(apps, schema_editor):
    Estoque = apps.get_model("estoque", "Estoque")
    for estoque in Estoque.objects.select_related("produto").iterator(chunk_size=500):
        estoque.custo_medio = estoque.produto.preco_custo or 0
        estoque.save(update_fields=["custo_medio"])


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_alter_composicaoproduto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='custo_medio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.RunPython(preencher_custo_medio, migrations.RunPython.noop),
    ]
