# Generated by Django 6.0.6 on 2026-08-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0021_estoque_custo_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventarioestoque',
            name='quantidade_contada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
