# Generated by Django 6.0.6 on 2026-08-31 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('estoque', '0022_alter_iteminventarioestoque_quantidade_contada'),
        ('produtos', '0015_versaoprecoproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoEstoqueContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('criterio_custo', models.CharField(default='CUSTO_MEDIO_PONDERADO_MOVEL', max_length=60)),
                ('total_itens', models.PositiveIntegerField(default=0)),
                ('valor_total_custo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('capturado_em', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_estoque_contabeis', to='empresas.filial')),
            ],
            options={
                'ordering': ['-data_referencia', 'filial__nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemFechamentoEstoqueContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=80)),
                ('codigo_barras', models.CharField(blank=True, max_length=80)),
                ('nome_produto', models.CharField(max_length=255)),
                ('ncm', models.CharField(blank=True, max_length=10)),
                ('cest', models.CharField(blank=True, max_length=10)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade_fisica', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, max_digits=14)),
                ('custo_medio', models.DecimalField(decimal_places=6, max_digits=14)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.fechamentoestoquecontabil')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_estoque_contabeis', to='produtos.produto')),
            ],
            options={
                'ordering': ['nome_produto', 'produto_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fechamentoestoquecontabil',
            constraint=models.UniqueConstraint(fields=('filial', 'data_referencia'), name='estoque_fech_contabil_filial_data_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemfechamentoestoquecontabil',
            constraint=models.UniqueConstraint(fields=('fechamento', 'produto'), name='estoque_item_fech_contabil_prod_uniq'),
        ),
    ]
