# Generated by Django 6.0.6 on 2026-08-31 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_fechamentoestoquecontabil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentoestoquecontabil',
            name='capturado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_estoque_contabeis_capturados', to=settings.AUTH_USER_MODEL),
        ),
    ]
