# Generated by Django 6.0.6 on 2026-08-31 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_fechamentoestoquecontabil_capturado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loteestoque',
            name='tratamento_validade_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='tratamento_validade_observacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='tratamento_validade_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tratamentos_validade_lote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='tratamento_validade_status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('SEPARADO', 'Separado para análise'), ('DEVOLUCAO_PLANEJADA', 'Devolução planejada'), ('PROMOCAO_PLANEJADA', 'Promoção planejada'), ('DESCARTE_PLANEJADO', 'Descarte planejado')], default='NAO_INICIADO', max_length=30),
        ),
    ]
