# Generated by Django 6.0.6 on 2026-08-31 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_loteestoque_tratamento_validade_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdaestoque',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perdas', to='estoque.loteestoque'),
        ),
        migrations.AlterField(
            model_name='loteestoque',
            name='tratamento_validade_status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('SEPARADO', 'Separado para análise'), ('DEVOLUCAO_PLANEJADA', 'Devolução planejada'), ('PROMOCAO_PLANEJADA', 'Promoção planejada'), ('DESCARTE_PLANEJADO', 'Descarte planejado'), ('BAIXA_CONCLUIDA', 'Baixa concluída')], default='NAO_INICIADO', max_length=30),
        ),
    ]
