# Generated by Django 6.0.6 on 2026-08-31 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('estoque', '0026_perdaestoque_lote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaFisicaValidadeLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial_id_snapshot', models.PositiveBigIntegerField()),
                ('filial_nome_snapshot', models.CharField(max_length=150)),
                ('produto_id_snapshot', models.PositiveBigIntegerField()),
                ('produto_nome_snapshot', models.CharField(max_length=200)),
                ('produto_codigo_barras_snapshot', models.CharField(blank=True, max_length=50)),
                ('lote_codigo_snapshot', models.CharField(max_length=60)),
                ('validade_snapshot', models.DateField()),
                ('quantidade_sistema_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_observada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('diferenca_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tratamento_status_snapshot', models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('SEPARADO', 'Separado para análise'), ('DEVOLUCAO_PLANEJADA', 'Devolução planejada'), ('PROMOCAO_PLANEJADA', 'Promoção planejada'), ('DESCARTE_PLANEJADO', 'Descarte planejado'), ('BAIXA_CONCLUIDA', 'Baixa concluída')], max_length=30)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('conferido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo_sha256', models.CharField(max_length=64, unique=True)),
                ('conferido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_fisicas_validade', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_fisicas_validade', to='empresas.empresa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_validade', to='estoque.loteestoque')),
            ],
            options={
                'ordering': ['-conferido_em', '-id'],
                'indexes': [models.Index(fields=['lote', 'conferido_em'], name='est_conf_val_lote_em_idx'), models.Index(fields=['empresa', 'conferido_em'], name='est_conf_val_emp_em_idx')],
            },
        ),
    ]
