# Generated by Django 6.0.6 on 2026-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0027_conferenciafisicavalidadelote'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioestoque',
            name='chave_origem',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventarioestoque',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('RISCO', 'Fila de risco'), ('DIVERGENCIA_VALIDADE', 'Divergência de validade')], default='MANUAL', max_length=30),
        ),
    ]
