# Generated by Django 6.0.6 on 2026-08-31 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0028_inventarioestoque_chave_origem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemItemInventarioValidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origens_inventario', to='estoque.conferenciafisicavalidadelote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origens_validade', to='estoque.iteminventarioestoque')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origens_inventario_validade', to='estoque.loteestoque')),
            ],
            options={
                'ordering': ['item_id', 'conferencia_id'],
                'constraints': [models.UniqueConstraint(fields=('item', 'conferencia'), name='est_item_inv_conf_val_unica')],
            },
        ),
    ]
