# Generated by Django 6.0.6 on 2026-08-31 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_origemiteminventariovalidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscopoLoteInventarioValidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escopos_validade', to='estoque.iteminventarioestoque')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escopos_inventario_validade', to='estoque.loteestoque')),
                ('origem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escopo_contagem', to='estoque.origemiteminventariovalidade')),
            ],
            options={
                'ordering': ['item_id', 'lote_id'],
            },
        ),
        migrations.CreateModel(
            name='ContagemLoteInventarioValidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_contada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('contado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo_sha256', models.CharField(max_length=64, unique=True)),
                ('contado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contagens_lote_inventario_validade', to=settings.AUTH_USER_MODEL)),
                ('escopo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contagens', to='estoque.escopoloteinventariovalidade')),
            ],
            options={
                'ordering': ['-contado_em', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='escopoloteinventariovalidade',
            constraint=models.UniqueConstraint(fields=('item', 'lote'), name='est_item_inv_lote_val_unico'),
        ),
        migrations.AddIndex(
            model_name='contagemloteinventariovalidade',
            index=models.Index(fields=['escopo', 'contado_em'], name='est_cont_inv_val_esc_em_idx'),
        ),
    ]
