# Generated by Django 6.0.6 on 2026-08-31 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0030_escopoloteinventariovalidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loteestoque',
            name='quantidade_acrescimos_auditados',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='RetificacaoCapacidadeLoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_inicial_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('capacidade_adicional_anterior', models.DecimalField(decimal_places=3, max_digits=12)),
                ('acrescimo_autorizado', models.DecimalField(decimal_places=3, max_digits=12)),
                ('nova_capacidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_contada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('justificativa', models.CharField(max_length=255)),
                ('aplicado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo_sha256', models.CharField(max_length=64, unique=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes_capacidade_lote_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('contagem', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retificacao_capacidade', to='estoque.contagemloteinventariovalidade')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes_capacidade_lote', to='estoque.inventarioestoque')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes_capacidade', to='estoque.loteestoque')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes_capacidade_lote_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aplicado_em', '-id'],
            },
        ),
    ]
