# Generated by Django 6.0.6 on 2026-08-31 18:40

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preparar_tentativas_e_prazos(apps, schema_editor):
    InventarioEstoque = apps.get_model("estoque", "InventarioEstoque")
    InventarioEstoque.objects.filter(
        chave_origem__isnull=False,
        chave_origem_base__isnull=True,
    ).update(chave_origem_base=models.F("chave_origem"))
    InventarioEstoque.objects.filter(
        origem="DIVERGENCIA_VALIDADE",
        status="ABERTO",
        expira_em__isnull=True,
    ).update(expira_em=models.F("criado_em") + timedelta(hours=24))

class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0031_loteestoque_quantidade_acrescimos_auditados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioestoque',
            name='chave_origem_base',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='inventarioestoque',
            name='encerrado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventarioestoque',
            name='encerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_estoque_encerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventarioestoque',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventarioestoque',
            name='motivo_encerramento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            preparar_tentativas_e_prazos,
            migrations.RunPython.noop,
        ),        migrations.AlterField(
            model_name='inventarioestoque',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('APLICADO', 'Aplicado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='ABERTO', max_length=20),
        ),
    ]
