# Generated by Django 6.0.6 on 2026-08-31 19:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0032_inventarioestoque_chave_origem_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoManutencaoInventarioValidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execucao_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha')], max_length=10)),
                ('iniciada_em', models.DateTimeField()),
                ('finalizada_em', models.DateTimeField()),
                ('expirados_total', models.PositiveIntegerField(default=0)),
                ('erro_codigo', models.CharField(blank=True, max_length=100)),
                ('erro_resumo', models.CharField(blank=True, max_length=255)),
                ('conteudo_sha256', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-finalizada_em', '-id'],
            },
        ),
    ]
