# Generated by Django 6.0.6 on 2026-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0033_execucaomanutencaoinventariovalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoloteestoque',
            name='lote_codigo_snapshot',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='movimentacaoloteestoque',
            name='lote_validade_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoloteestoque',
            name='snapshot_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='movimentacaoloteestoque',
            name='tratamento_status_snapshot',
            field=models.CharField(blank=True, choices=[('NAO_INICIADO', 'Não iniciado'), ('SEPARADO', 'Separado para análise'), ('DEVOLUCAO_PLANEJADA', 'Devolução planejada'), ('PROMOCAO_PLANEJADA', 'Promoção planejada'), ('DESCARTE_PLANEJADO', 'Descarte planejado'), ('BAIXA_CONCLUIDA', 'Baixa concluída')], max_length=30),
        ),
    ]
