# Generated by Django 6.0.6 on 2026-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0034_snapshot_historico_movimentacao_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenciafisicavalidadelote',
            name='custo_unitario_snapshot',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='desmembramentoproduto',
            name='custo_total_origem',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemdesmembramentoproduto',
            name='custo_total',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemdesmembramentoproduto',
            name='custo_unitario_calculado',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemproducaocomposicaoproduto',
            name='custo_total',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemproducaocomposicaoproduto',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loteestoque',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoloteestoque',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='perdaestoque',
            name='custo_unitario_no_momento',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='producaocomposicaoproduto',
            name='custo_total',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
