# Generated by Django 6.0.6 on 2026-06-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=80, unique=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=80)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo'), ('G', 'Grama'), ('L', 'Litro'), ('M', 'Metro')], default='UN', max_length=3)),
                ('produto_pesavel', models.BooleanField(default=False)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('vendido_no_pdv', models.BooleanField(default=True)),
                ('vendido_no_marketplace', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.marca')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
