# Generated by Django 6.0.6 on 2026-07-06 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produtoimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='Envie uma imagem PNG, JPG ou JPEG.')]),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(upload_to='produtos/galeria/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='Envie uma imagem PNG, JPG ou JPEG.')]),
        ),
    ]
