# Generated by Django 6.0.6 on 2026-07-31 12:01

from django.db import migrations, models


def preencher_codigos_internos(apps, schema_editor):
    Produto = apps.get_model("produtos", "Produto")
    usados = set()

    for produto in Produto._base_manager.order_by("id").iterator():
        codigo = (produto.codigo_interno or "").strip().upper()
        if not codigo or codigo in usados:
            numero = max(1, produto.pk)
            codigo = f"PRD-{numero:06d}"
            while codigo in usados:
                numero += 1
                codigo = f"PRD-{numero:06d}"
        usados.add(codigo)
        if produto.codigo_interno != codigo:
            Produto._base_manager.filter(pk=produto.pk).update(codigo_interno=codigo)


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0006_corrigir_nome_maca_corrompido"),
    ]

    operations = [
        migrations.RunPython(preencher_codigos_internos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("codigo_interno", ""), _negated=True),
                fields=("codigo_interno",),
                name="produtos_codigo_interno_unico_preenchido",
            ),
        ),
    ]
