# Generated by Django 6.0.6 on 2026-07-31 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_produtos_codigo_interno_unico_preenchido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fator_conversao_compra',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Quantidade da unidade base contida em uma unidade de compra.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade na unidade base'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso bruto (kg)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso líquido (kg)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_compra',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo'), ('G', 'Grama'), ('L', 'Litro'), ('M', 'Metro'), ('CX', 'Caixa'), ('FD', 'Fardo'), ('PCT', 'Pacote')], default='UN', max_length=3, verbose_name='Unidade de compra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo'), ('G', 'Grama'), ('L', 'Litro'), ('M', 'Metro'), ('CX', 'Caixa'), ('FD', 'Fardo'), ('PCT', 'Pacote')], default='UN', max_length=3),
        ),
        migrations.CreateModel(
            name='CodigoBarrasProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True, verbose_name='Código de barras')),
                ('tipo', models.CharField(choices=[('UNIDADE', 'Unidade'), ('PACOTE', 'Pacote'), ('FARDO', 'Fardo'), ('CAIXA', 'Caixa'), ('OUTRO', 'Outro')], default='UNIDADE', max_length=20)),
                ('fator_conversao', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantidade na unidade base')),
                ('permite_venda', models.BooleanField(default=True, verbose_name='Pode ser usado no PDV')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_adicionais', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Código de barras do produto',
                'verbose_name_plural': 'Códigos de barras dos produtos',
                'ordering': ['produto', 'tipo', 'codigo'],
            },
        ),
    ]
