# Generated by Django 6.0.6 on 2026-07-31 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_produto_fator_conversao_compra_produto_peso_bruto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nivel',
            field=models.CharField(choices=[('DEPARTAMENTO', 'Departamento'), ('SECAO', 'Seção'), ('GRUPO', 'Grupo'), ('SUBGRUPO', 'Subgrupo')], default='GRUPO', max_length=20, verbose_name='Nível comercial'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhas', to='produtos.categoria', verbose_name='Classificação superior'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('MERCADORIA', 'Mercadoria para revenda'), ('INSUMO', 'Insumo'), ('SERVICO', 'Serviço'), ('IMOBILIZADO', 'Imobilizado'), ('MATERIAL_CONSUMO', 'Material de consumo')], default='MERCADORIA', max_length=20, verbose_name='Tipo comercial'),
        ),
    ]
