# Generated by Django 6.0.6 on 2026-07-31 15:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_atribuir_empresa_fornecedores_existentes'),
        ('produtos', '0009_categoria_nivel_categoria_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='margem_desejada_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.99)], verbose_name='Margem desejada (%)'),
        ),
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_no_fornecedor', models.CharField(blank=True, max_length=80, verbose_name='Código no fornecedor')),
                ('ultimo_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Último custo cotado')),
                ('principal', models.BooleanField(default=False, verbose_name='Fornecedor principal')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_vinculados', to='fornecedores.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_vinculados', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Fornecedor do produto',
                'verbose_name_plural': 'Fornecedores do produto',
                'ordering': ['-principal', 'fornecedor__razao_social'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'fornecedor'), name='produto_fornecedor_unico')],
            },
        ),
    ]
