# Generated by Django 6.0.6 on 2026-07-31 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_alter_empresa_modo_implantacao'),
        ('produtos', '0010_produto_margem_desejada_percentual_produtofornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorBalanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Código do setor')),
                ('nome', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setores_balanca', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Setor de balança',
                'verbose_name_plural': 'Setores de balança',
                'ordering': ['empresa__nome_fantasia', 'codigo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoBalancaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)], verbose_name='PLU')),
                ('tara_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tara (kg)')),
                ('validade_dias', models.PositiveSmallIntegerField(default=0, verbose_name='Validade (dias)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_balanca', to='empresas.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_balanca', to='produtos.produto')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_configurados', to='produtos.setorbalanca')),
            ],
            options={
                'verbose_name': 'Configuração de balança do produto',
                'verbose_name_plural': 'Configurações de balança dos produtos',
                'ordering': ['setor__empresa__nome_fantasia', 'setor__codigo', 'plu'],
            },
        ),
        migrations.AddConstraint(
            model_name='setorbalanca',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='setor_balanca_codigo_unico_empresa'),
        ),
        migrations.AddConstraint(
            model_name='setorbalanca',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='setor_balanca_nome_unico_empresa'),
        ),
        migrations.AddConstraint(
            model_name='configuracaobalancaproduto',
            constraint=models.UniqueConstraint(fields=('empresa', 'plu'), name='produto_balanca_plu_unico_empresa'),
        ),
        migrations.AddConstraint(
            model_name='configuracaobalancaproduto',
            constraint=models.UniqueConstraint(fields=('produto', 'empresa'), name='produto_balanca_unico_empresa'),
        ),
    ]
