# Generated by Django 6.0.6 on 2026-07-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_setorbalanca_configuracaobalancaproduto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produtos_similares',
            field=models.ManyToManyField(blank=True, help_text='Alternativas comerciais que podem substituir ou complementar este produto.', to='produtos.produto'),
        ),
        migrations.CreateModel(
            name='InformacaoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.CharField(choices=[('100G', '100 g'), ('100ML', '100 ml')], default='100G', max_length=5, verbose_name='Valores declarados por')),
                ('porcao_quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Porção')),
                ('porcao_unidade', models.CharField(blank=True, help_text='Ex.: g, ml ou unidade.', max_length=10, verbose_name='Unidade da porção')),
                ('medida_caseira', models.CharField(blank=True, help_text='Ex.: 1 colher, 2 fatias ou 1 unidade.', max_length=120)),
                ('porcoes_por_embalagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_energetico_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor energético (kcal)')),
                ('carboidratos_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carboidratos (g)')),
                ('acucares_totais_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Açúcares totais (g)')),
                ('acucares_adicionados_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Açúcares adicionados (g)')),
                ('proteinas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Proteínas (g)')),
                ('gorduras_totais_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gorduras totais (g)')),
                ('gorduras_saturadas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gorduras saturadas (g)')),
                ('gorduras_trans_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gorduras trans (g)')),
                ('fibra_alimentar_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fibra alimentar (g)')),
                ('sodio_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sódio (mg)')),
                ('ingredientes', models.TextField(blank=True)),
                ('alergicos', models.TextField(blank=True, verbose_name='Alérgicos')),
                ('gluten', models.CharField(blank=True, choices=[('', 'Não informado'), ('CONTEM', 'Contém'), ('NAO_CONTEM', 'Não contém')], max_length=12, verbose_name='Glúten')),
                ('lactose', models.CharField(blank=True, choices=[('', 'Não informado'), ('CONTEM', 'Contém'), ('NAO_CONTEM', 'Não contém')], max_length=12, verbose_name='Lactose')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacao_nutricional', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Informação nutricional',
                'verbose_name_plural': 'Informações nutricionais',
            },
        ),
    ]
