# Generated by Django 6.0.6 on 2026-07-31 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_produto_produtos_similares_informacaonutricional'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_cofins',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota COFINS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_fcp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota FCP (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_ipi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota IPI (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_pis',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alíquota PIS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='classificacao_tributaria_ibs_cbs',
            field=models.CharField(blank=True, max_length=6, verbose_name='Classificação tributária IBS/CBS (cClassTrib)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_beneficio_fiscal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código de benefício fiscal (cBenef)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_cofins',
            field=models.CharField(blank=True, max_length=2, verbose_name='CST COFINS'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_ibs_cbs',
            field=models.CharField(blank=True, max_length=3, verbose_name='CST IBS/CBS'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_ipi',
            field=models.CharField(blank=True, max_length=2, verbose_name='CST IPI'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_pis',
            field=models.CharField(blank=True, max_length=2, verbose_name='CST PIS'),
        ),
        migrations.AddField(
            model_name='produto',
            name='reducao_base_icms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Redução da base ICMS (%)'),
        ),
    ]
