# Generated by Django 6.0.6 on 2026-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_produto_aliquota_cofins_produto_aliquota_fcp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_enquadramento_ipi',
            field=models.CharField(blank=True, max_length=3, verbose_name='Código de enquadramento IPI (cEnq)'),
        ),
    ]
