# Generated by Django 6.0.6 on 2026-08-17 19:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_produto_codigo_enquadramento_ipi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoPrecoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('preco_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_novo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('vigencia_inicio', models.DateTimeField(verbose_name='Início da vigência')),
                ('motivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versoes_preco_canceladas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes_preco_criadas', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes_preco', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Versão de preço do produto',
                'verbose_name_plural': 'Versões de preço dos produtos',
                'ordering': ['-vigencia_inicio', '-versao'],
                'indexes': [models.Index(fields=['produto', 'status', 'vigencia_inicio'], name='produto_preco_vigente_idx')],
                'constraints': [models.UniqueConstraint(fields=('produto', 'versao'), name='produto_versao_preco_unica'), models.CheckConstraint(condition=models.Q(('preco_novo__gt', 0)), name='produto_versao_preco_positivo')],
            },
        ),
    ]
