# Generated by Django 6.0.6 on 2026-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_versaoprecoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='ultimo_custo',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Último custo cotado'),
        ),
    ]
