# Generated by Django 6.0.6 on 2026-09-30 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_alter_produto_preco_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='reducao_base_icms',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Redução da base ICMS (%)'),
        ),
    ]
