# Generated by Django 6.0.6 on 2026-07-01 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('vendas', '0003_devolucaovenda_itemdevolucaovenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, unique=True)),
                ('cfop', models.CharField(blank=True, max_length=10)),
                ('tipo_documento', models.CharField(choices=[('NFCE', 'NFC-e'), ('NFE', 'NF-e')], default='NFCE', max_length=10)),
                ('movimenta_estoque', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologacao'), ('PRODUCAO', 'Producao')], default='HOMOLOGACAO', max_length=20)),
                ('regime_tributario', models.CharField(blank=True, max_length=80)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30)),
                ('csc_id', models.CharField(blank=True, max_length=20, verbose_name='ID CSC')),
                ('csc_token', models.CharField(blank=True, max_length=255, verbose_name='Token CSC')),
                ('certificado_nome', models.CharField(blank=True, max_length=255)),
                ('certificado_validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_fiscal', to='empresas.filial')),
            ],
            options={
                'ordering': ['filial__nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('NFCE', 'NFC-e'), ('NFE', 'NF-e')], default='NFCE', max_length=10)),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologacao'), ('PRODUCAO', 'Producao')], default='HOMOLOGACAO', max_length=20)),
                ('serie', models.PositiveIntegerField(default=1)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=60)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PRONTO', 'Pronto para transmissao'), ('EMITIDO', 'Emitido'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('INUTILIZADO', 'Inutilizado')], default='RASCUNHO', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mensagem_retorno', models.TextField(blank=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='vendas.venda')),
                ('natureza_operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='fiscal.naturezaoperacao')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('filial', 'tipo_documento', 'serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SerieFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('NFCE', 'NFC-e'), ('NFE', 'NF-e')], default='NFCE', max_length=10)),
                ('serie', models.PositiveIntegerField(default=1)),
                ('proximo_numero', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_fiscais', to='empresas.filial')),
            ],
            options={
                'ordering': ['filial__nome', 'tipo_documento', 'serie'],
                'unique_together': {('filial', 'tipo_documento', 'serie')},
            },
        ),
    ]
