# Generated by Django 6.0.6 on 2026-07-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_configuracaofiscal_certificado_a1_criptografado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='xml_conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='xml_gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
