# Generated by Django 6.0.6 on 2026-07-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_documentofiscal_xml_conteudo_and_more'),
        ('marketplace', '0005_pedidoonline_documento_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='pedido_online',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='marketplace.pedidoonline'),
        ),
    ]
