# Generated by Django 6.0.6 on 2026-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_contingencia_offline_nfce'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='certificado_serial_assinatura',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='xml_assinado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
