# Generated by Django 6.0.6 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_documentofiscal_fila_transmissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaofiscal',
            name='permite_contingencia_offline',
            field=models.BooleanField(default=False, help_text='Habilite somente quando a UF e a situação operacional permitirem a contingência offline.', verbose_name='Permite contingência offline NFC-e'),
        ),
    ]
