# Generated by Django 6.0.6 on 2026-08-03 11:55

from django.db import migrations, models


def preencher_crt_existente(apps, schema_editor):
    ConfiguracaoFiscal = apps.get_model("fiscal", "ConfiguracaoFiscal")
    for configuracao in ConfiguracaoFiscal.objects.all().iterator():
        regime = (configuracao.regime_tributario or "").upper()
        if "MEI" in regime:
            crt = "4"
        elif "SIMPLES" in regime and ("EXCESSO" in regime or "SUBLIMITE" in regime):
            crt = "2"
        elif "SIMPLES" in regime:
            crt = "1"
        else:
            crt = "3"
        ConfiguracaoFiscal.objects.filter(pk=configuracao.pk).update(crt=crt)

class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_alter_configuracaofiscal_permite_contingencia_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='crt',
            field=models.CharField(choices=[('1', '1 - Simples Nacional'), ('2', '2 - Simples Nacional, excesso de sublimite'), ('3', '3 - Regime Normal'), ('4', '4 - Simples Nacional, MEI')], default='3', max_length=1, verbose_name='Código de Regime Tributário (CRT)'),
        ),        migrations.RunPython(preencher_crt_existente, migrations.RunPython.noop),
    ]
