# Generated by Django 6.0.6 on 2026-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_configuracaofiscal_crt'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturezaoperacao',
            name='ipi_compoe_base_icms',
            field=models.BooleanField(default=False, help_text='Defina conforme a operação e o destinatário.', verbose_name='IPI compõe a base do ICMS'),
        ),
        migrations.AddField(
            model_name='naturezaoperacao',
            name='ipi_compoe_base_pis_cofins',
            field=models.BooleanField(default=False, help_text='Defina conforme a orientação contábil da operação.', verbose_name='IPI compõe a base de PIS/COFINS'),
        ),
        migrations.AddField(
            model_name='naturezaoperacao',
            name='ipi_incluso_preco',
            field=models.BooleanField(default=False, help_text='Exige validação contábil. Mantém o total cobrado e destaca o IPI no XML.', verbose_name='IPI tributado já incluído no preço'),
        ),
    ]
