# Generated by Django 6.0.6 on 2026-08-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0013_naturezaoperacao_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='cancelamento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='mensagem_cancelamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='protocolo_cancelamento',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
