# Generated by Django 6.0.6 on 2026-08-03 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_lancamentofinanceirosincronizado'),
        ('fiscal', '0014_documentofiscal_cancelamento_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InutilizacaoNumeracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('NFCE', 'NFC-e'), ('NFE', 'NF-e')], max_length=10)),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologacao'), ('PRODUCAO', 'Producao')], max_length=20)),
                ('ano', models.PositiveSmallIntegerField()),
                ('serie', models.PositiveIntegerField()),
                ('numero_inicial', models.PositiveIntegerField()),
                ('numero_final', models.PositiveIntegerField()),
                ('justificativa', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('mensagem_retorno', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inutilizacoes_numeracao_fiscal', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inutilizacoes_numeracao_fiscal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['filial', 'tipo_documento', 'ano', 'serie'], name='fiscal_inut_faixa_idx')],
            },
        ),
    ]
