# Generated by Django 6.0.6 on 2026-08-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0015_inutilizacaonumeracaofiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='consulta_sefaz_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='mensagem_consulta_sefaz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PRONTO', 'Pronto para transmissao'), ('EMITIDO', 'Emitido'), ('REJEITADO', 'Rejeitado'), ('CONTINGENCIA', 'Contingencia offline'), ('CANCELADO', 'Cancelado'), ('DENEGADO', 'Denegado'), ('INUTILIZADO', 'Inutilizado')], default='RASCUNHO', max_length=20),
        ),
    ]
