# Generated by Django 6.0.6 on 2026-08-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0016_documentofiscal_consulta_sefaz_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='aguardando_consulta_sefaz',
            field=models.BooleanField(default=False),
        ),
    ]
