# Generated by Django 6.0.6 on 2026-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0017_documentofiscal_aguardando_consulta_sefaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='tentativas_consulta_sefaz',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
