# Generated by Django 6.0.6 on 2026-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0018_documentofiscal_tentativas_consulta_sefaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='ibs_cbs_versao_leiaute',
            field=models.CharField(blank=True, help_text='Identifique a Nota Técnica e o pacote XSD homologados para esta filial.', max_length=80, verbose_name='Versão do leiaute IBS/CBS'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='ibs_cbs_vigencia_inicio',
            field=models.DateField(blank=True, help_text='Data aprovada pelo contador para iniciar a validação da nova classificação tributária.', null=True, verbose_name='Início da vigência IBS/CBS'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='modo_transicao_ibs_cbs',
            field=models.CharField(choices=[('LEGADO', 'Legado (ICMS, PIS e COFINS)'), ('PREPARACAO', 'Preparação IBS/CBS'), ('EMISSAO_HOMOLOGADA', 'Emissão IBS/CBS homologada')], default='LEGADO', help_text='Preparação exige CST IBS/CBS e cClassTrib nos produtos após a vigência. A emissão somente pode ser ativada depois da homologação do schema e do adaptador fiscal.', max_length=24, verbose_name='Modo de transição IBS/CBS'),
        ),
    ]
