# Generated by Django 6.0.6 on 2026-08-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0019_configuracaofiscal_ibs_cbs_versao_leiaute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomologacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=160)),
                ('evidencia_referencia', models.CharField(blank=True, help_text='Número de chamado, URL protegida, protocolo ou caminho da evidência de homologação.', max_length=500)),
                ('observacoes', models.TextField(blank=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homologacoes_fiscais_concluidas', to=settings.AUTH_USER_MODEL)),
                ('configuracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homologacao_tecnica', to='fiscal.configuracaofiscal')),
            ],
            options={
                'verbose_name': 'homologação fiscal',
                'verbose_name_plural': 'homologações fiscais',
                'ordering': ['configuracao__filial__nome'],
            },
        ),
    ]
