# Generated by Django 6.0.6 on 2026-08-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('fiscal', '0020_homologacaofiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDistribuicaoDFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Caixa de entrada de DF-e ativa')),
                ('ultimo_nsu', models.CharField(blank=True, max_length=20, verbose_name='Último NSU processado')),
                ('ultima_consulta_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_distribuicao_dfe', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'configuração de distribuição DF-e',
                'verbose_name_plural': 'configurações de distribuição DF-e',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDFeRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=44)),
                ('nsu', models.CharField(blank=True, max_length=20)),
                ('schema', models.CharField(blank=True, max_length=80)),
                ('emitente_cnpj', models.CharField(blank=True, max_length=14)),
                ('emitente_nome', models.CharField(blank=True, max_length=255)),
                ('numero_documento', models.CharField(blank=True, max_length=30)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('XML_DISPONIVEL', 'XML disponível'), ('VINCULADO', 'Vinculado à entrada'), ('IGNORADO', 'Ignorado')], default='NOVO', max_length=24)),
                ('origem', models.CharField(default='MANUAL', max_length=24)),
                ('xml_conteudo', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_dfe_recebidos', to='empresas.empresa')),
                ('filial_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_dfe_recebidos', to='empresas.filial')),
            ],
            options={
                'ordering': ['-recebido_em'],
                'indexes': [models.Index(fields=['empresa', 'status', '-recebido_em'], name='fiscal_dfe_empresa_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'chave_acesso'), name='fiscal_dfe_empresa_chave_uniq')],
            },
        ),
    ]
