# Generated by Django 6.0.6 on 2026-08-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_entradacompra_conferencia_fisica_em_and_more'),
        ('fiscal', '0021_configuracaodistribuicaodfe_documentodferecebido'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodferecebido',
            name='entrada_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_dfe_recebido', to='compras.entradacompra'),
        ),
    ]
