# Generated by Django 6.0.6 on 2026-08-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('fiscal', '0022_documentodferecebido_entrada_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleDistribuicaoDFeFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_nsu', models.CharField(blank=True, max_length=20, verbose_name='Último NSU processado')),
                ('max_nsu', models.CharField(blank=True, max_length=20, verbose_name='Maior NSU disponível')),
                ('ultima_consulta_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_filiais', to='fiscal.configuracaodistribuicaodfe')),
                ('filial', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='controle_distribuicao_dfe', to='empresas.filial')),
            ],
            options={
                'verbose_name': 'controle de distribuição DF-e por filial',
                'verbose_name_plural': 'controles de distribuição DF-e por filial',
                'ordering': ['filial__nome'],
            },
        ),
    ]
