# Generated by Django 6.0.6 on 2026-08-20 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0023_controledistribuicaodfefilial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteAtualizacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('nome', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('NOVA', 'Aguardando primeira consulta'), ('OK', 'Atualizada'), ('ERRO', 'Falha na consulta')], default='NOVA', max_length=12)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('ultima_modificacao_http', models.CharField(blank=True, max_length=255)),
                ('conteudo_sha256', models.CharField(blank=True, max_length=64)),
                ('itens_snapshot', models.JSONField(blank=True, default=list)),
                ('ultima_consulta_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_alteracao_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fonte de atualização fiscal',
                'verbose_name_plural': 'fontes de atualização fiscal',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AlertaAtualizacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('titulo', models.CharField(max_length=500)),
                ('url_referencia', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('REVISADO', 'Revisado'), ('IGNORADO', 'Ignorado')], default='NOVO', max_length=12)),
                ('detectado_em', models.DateTimeField(auto_now_add=True)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atualizacao_fiscal_revisados', to=settings.AUTH_USER_MODEL)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='fiscal.fonteatualizacaofiscal')),
            ],
            options={
                'verbose_name': 'alerta de atualização fiscal',
                'verbose_name_plural': 'alertas de atualização fiscal',
                'ordering': ['-detectado_em'],
                'indexes': [models.Index(fields=['status', '-detectado_em'], name='fiscal_alerta_status_data_idx')],
                'constraints': [models.UniqueConstraint(fields=('fonte', 'fingerprint'), name='fiscal_alerta_fonte_fingerprint_uniq')],
            },
        ),
    ]
