# Generated by Django 6.0.6 on 2026-08-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('fiscal', '0024_monitor_atualizacoes_fiscais'),
    ]

    operations = [
        migrations.AddField(
            model_name='controledistribuicaodfefilial',
            name='proxima_consulta_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventoDFeRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsu', models.CharField(max_length=20)),
                ('schema', models.CharField(blank=True, max_length=80)),
                ('chave_acesso', models.CharField(blank=True, max_length=44)),
                ('tipo_evento', models.CharField(blank=True, max_length=20)),
                ('sequencia', models.PositiveIntegerField(default=1)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('xml_conteudo', models.TextField()),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_dfe_recebidos', to='empresas.empresa')),
                ('filial_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_dfe_recebidos', to='empresas.filial')),
            ],
            options={
                'verbose_name': 'evento DF-e recebido',
                'verbose_name_plural': 'eventos DF-e recebidos',
                'ordering': ['-recebido_em', '-id'],
                'indexes': [models.Index(fields=['empresa', '-recebido_em'], name='fiscal_evt_dfe_emp_data_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nsu'), name='fiscal_evento_dfe_empresa_nsu_uniq')],
            },
        ),
    ]
