# Generated by Django 6.0.6 on 2026-08-20 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('fiscal', '0025_controledistribuicaodfefilial_proxima_consulta_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestacaoDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('210200', 'Confirmação da operação'), ('210210', 'Ciência da operação'), ('210220', 'Desconhecimento da operação'), ('210240', 'Operação não realizada')], max_length=6)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('ERRO', 'Erro de transmissão')], default='PENDENTE', max_length=16)),
                ('justificativa', models.CharField(blank=True, max_length=255)),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologacao'), ('PRODUCAO', 'Producao')], max_length=20)),
                ('codigo_status', models.CharField(blank=True, max_length=10)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('mensagem', models.TextField(blank=True)),
                ('xml_envio', models.TextField(blank=True)),
                ('xml_retorno', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestacoes_destinatario', to='fiscal.documentodferecebido')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestacoes_destinatario', to='empresas.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestacoes_destinatario', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestacoes_destinatario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manifestação do destinatário',
                'verbose_name_plural': 'manifestações do destinatário',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['empresa', 'documento', '-criado_em'], name='fiscal_manif_emp_doc_idx')],
            },
        ),
    ]
