# Generated by Django 6.0.6 on 2026-08-20 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('fiscal', '0026_manifestacaodestinatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaCorrecaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveSmallIntegerField()),
                ('correcao', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('ERRO', 'Erro de transmissão')], default='PENDENTE', max_length=16)),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologacao'), ('PRODUCAO', 'Producao')], max_length=20)),
                ('codigo_status', models.CharField(blank=True, max_length=10)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('mensagem', models.TextField(blank=True)),
                ('xml_envio', models.TextField(blank=True)),
                ('xml_retorno', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_correcao', to='fiscal.documentofiscal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_correcao_fiscais', to='empresas.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_correcao_fiscais', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_correcao_fiscais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carta de Correção Eletrônica',
                'verbose_name_plural': 'Cartas de Correção Eletrônicas',
                'ordering': ['-sequencia', '-id'],
                'indexes': [models.Index(fields=['empresa', 'documento', '-sequencia'], name='fiscal_cce_emp_doc_seq_idx')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'sequencia'), name='fiscal_cce_documento_seq_uniq')],
            },
        ),
    ]
