# Generated by Django 6.0.6 on 2026-08-20 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('fiscal', '0027_cartacorrecaofiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCadastroContribuinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('tipo_documento', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF'), ('IE', 'Inscrição estadual')], max_length=4)),
                ('documento', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Consultado'), ('REJEITADA', 'Rejeitada'), ('ERRO', 'Erro de comunicação')], default='PENDENTE', max_length=16)),
                ('codigo_status', models.CharField(blank=True, max_length=10)),
                ('mensagem', models.TextField(blank=True)),
                ('ocorrencias', models.JSONField(blank=True, default=list)),
                ('xml_envio', models.TextField(blank=True)),
                ('xml_retorno', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_cadastro_fiscais', to='empresas.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_cadastro_fiscais', to='empresas.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_cadastro_fiscais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consulta de cadastro do contribuinte',
                'verbose_name_plural': 'consultas de cadastro dos contribuintes',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['empresa', 'filial', '-criado_em'], name='fiscal_cad_emp_fil_data_idx')],
            },
        ),
    ]
