# Generated by Django 6.0.6 on 2026-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0028_consultacadastrocontribuinte'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='provedor_emissao',
            field=models.CharField(choices=[('DESATIVADO', 'Emissão externa desativada'), ('PADRAO_SERVIDOR', 'Compatibilidade do servidor'), ('FOCUS', 'Integração Focus NFe'), ('SEFAZ_DIRETA_GO', 'Conexão direta SEFAZ - Goiás')], default='PADRAO_SERVIDOR', help_text='Seleção técnica exclusiva do Master. Credenciais permanecem no ambiente seguro do servidor.', max_length=24, verbose_name='Canal técnico de emissão'),
        ),
    ]
