# Generated by Django 6.0.6 on 2026-08-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0029_configuracaofiscal_provedor_emissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='confirmacoes_nao_localizado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
