# Generated by Django 6.0.6 on 2026-08-24 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0030_documentofiscal_confirmacoes_nao_localizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('XML_ENVIO', 'XML transmitido'), ('RETORNO_TRANSMISSAO', 'Retorno da transmissão'), ('XML_AUTORIZADO', 'XML autorizado'), ('RETORNO_CONSULTA', 'Retorno da consulta'), ('EVENTO_CANCELAMENTO_ENVIO', 'Pedido de cancelamento'), ('EVENTO_CANCELAMENTO_RETORNO', 'Retorno do cancelamento'), ('EVENTO_CCE_ENVIO', 'XML da CC-e transmitida'), ('EVENTO_CCE_RETORNO', 'XML de retorno da CC-e')], max_length=40)),
                ('canal', models.CharField(blank=True, max_length=40)),
                ('referencia', models.CharField(max_length=180)),
                ('chave_acesso', models.CharField(blank=True, max_length=44)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('conteudo', models.TextField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('anterior_sha256', models.CharField(blank=True, max_length=64)),
                ('cadeia_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_fiscais', to='fiscal.documentofiscal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_fiscais_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evidência fiscal imutável',
                'verbose_name_plural': 'evidências fiscais imutáveis',
                'ordering': ['sequencia', 'id'],
                'indexes': [models.Index(fields=['documento', 'tipo'], name='fiscal_evid_doc_tipo_idx')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'sequencia'), name='fiscal_evidencia_documento_seq_uniq'), models.UniqueConstraint(fields=('documento', 'tipo', 'referencia'), name='fiscal_evidencia_documento_ref_uniq')],
            },
        ),
    ]
