# Generated by Django 6.0.6 on 2026-08-28 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0031_evidenciafiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoBeneficioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('versao', models.CharField(max_length=100)),
                ('fonte_nome', models.CharField(max_length=255)),
                ('fonte_url', models.URLField(max_length=500)),
                ('fonte_sha256', models.CharField(max_length=64)),
                ('publicado_em', models.DateField(blank=True, null=True)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('quantidade_itens', models.PositiveIntegerField(default=0)),
                ('codigos_duplicados', models.JSONField(blank=True, default=list)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogos_beneficio_fiscal_importados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'catálogo de benefício fiscal',
                'verbose_name_plural': 'catálogos de benefícios fiscais',
                'ordering': ['uf', '-vigencia_inicio', '-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemBeneficioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('csts', models.JSONField(default=list)),
                ('dispositivo_legal', models.TextField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='fiscal.catalogobeneficiofiscal')),
            ],
            options={
                'verbose_name': 'item de benefício fiscal',
                'verbose_name_plural': 'itens de benefícios fiscais',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogobeneficiofiscal',
            index=models.Index(fields=['uf', 'ativo', 'vigencia_inicio', 'vigencia_fim'], name='fiscal_cbenef_vigencia_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogobeneficiofiscal',
            constraint=models.UniqueConstraint(fields=('uf', 'versao', 'fonte_sha256'), name='fiscal_cbenef_uf_versao_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='itembeneficiofiscal',
            index=models.Index(fields=['codigo'], name='fiscal_cbenef_codigo_idx'),
        ),
        migrations.AddConstraint(
            model_name='itembeneficiofiscal',
            constraint=models.UniqueConstraint(fields=('catalogo', 'codigo'), name='fiscal_cbenef_catalogo_codigo_uniq'),
        ),
    ]
