# Generated by Django 6.0.6 on 2026-08-28 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0032_catalogobeneficiofiscal_itembeneficiofiscal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoNCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=120)),
                ('referencia_em', models.DateField()),
                ('ato', models.CharField(max_length=255)),
                ('fonte_nome', models.CharField(max_length=255)),
                ('fonte_url', models.URLField(max_length=500)),
                ('fonte_sha256', models.CharField(max_length=64)),
                ('ativo', models.BooleanField(default=False)),
                ('quantidade_itens', models.PositiveIntegerField(default=0)),
                ('quantidade_linhas_origem', models.PositiveIntegerField(default=0)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogos_ncm_importados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'catálogo NCM',
                'verbose_name_plural': 'catálogos NCM',
                'ordering': ['-referencia_em', '-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemNCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('codigo_formatado', models.CharField(max_length=12)),
                ('descricao', models.TextField()),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('ato_inicio', models.CharField(blank=True, max_length=255)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='fiscal.catalogoncm')),
            ],
            options={
                'verbose_name': 'item NCM',
                'verbose_name_plural': 'itens NCM',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogoncm',
            index=models.Index(fields=['ativo', 'referencia_em'], name='fiscal_ncm_ativo_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogoncm',
            constraint=models.UniqueConstraint(fields=('versao', 'fonte_sha256'), name='fiscal_ncm_versao_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='itemncm',
            index=models.Index(fields=['codigo'], name='fiscal_ncm_codigo_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemncm',
            constraint=models.UniqueConstraint(fields=('catalogo', 'codigo'), name='fiscal_ncm_catalogo_codigo_uniq'),
        ),
    ]
