# Generated by Django 6.0.6 on 2026-08-31 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0033_catalogoncm_itemncm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=120)),
                ('referencia_em', models.DateField()),
                ('ato', models.CharField(max_length=255)),
                ('fonte_nome', models.CharField(max_length=255)),
                ('fonte_url', models.URLField(max_length=500)),
                ('fonte_sha256', models.CharField(max_length=64)),
                ('ativo', models.BooleanField(default=False)),
                ('quantidade_itens', models.PositiveIntegerField(default=0)),
                ('quantidade_linhas_origem', models.PositiveIntegerField(default=0)),
                ('quantidade_tabelas_origem', models.PositiveIntegerField(default=0)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogos_cest_importados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'catálogo CEST',
                'verbose_name_plural': 'catálogos CEST',
                'ordering': ['-referencia_em', '-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemCEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('codigo_formatado', models.CharField(max_length=9)),
                ('item', models.CharField(max_length=20)),
                ('segmento_codigo', models.CharField(max_length=2)),
                ('segmento_nome', models.CharField(max_length=255)),
                ('ncm_sh_original', models.CharField(blank=True, max_length=500)),
                ('ncm_prefixos', models.JSONField(default=list)),
                ('descricao', models.TextField()),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='fiscal.catalogocest')),
            ],
            options={
                'verbose_name': 'item CEST',
                'verbose_name_plural': 'itens CEST',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogocest',
            index=models.Index(fields=['ativo', 'referencia_em'], name='fiscal_cest_ativo_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogocest',
            constraint=models.UniqueConstraint(fields=('versao', 'fonte_sha256'), name='fiscal_cest_versao_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='itemcest',
            index=models.Index(fields=['codigo'], name='fiscal_cest_codigo_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcest',
            constraint=models.UniqueConstraint(fields=('catalogo', 'codigo'), name='fiscal_cest_catalogo_codigo_uniq'),
        ),
    ]
