# Generated by Django 6.0.6 on 2026-08-31 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0034_catalogocest_itemcest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCFOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=120)),
                ('referencia_em', models.DateField()),
                ('ato', models.CharField(max_length=255)),
                ('fonte_nome', models.CharField(max_length=255)),
                ('fonte_url', models.URLField(max_length=500)),
                ('fonte_sha256', models.CharField(max_length=64)),
                ('ativo', models.BooleanField(default=False)),
                ('quantidade_itens', models.PositiveIntegerField(default=0)),
                ('quantidade_linhas_origem', models.PositiveIntegerField(default=0)),
                ('quantidade_agrupadores', models.PositiveIntegerField(default=0)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogos_cfop_importados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'catálogo CFOP',
                'verbose_name_plural': 'catálogos CFOP',
                'ordering': ['-referencia_em', '-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemCFOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('codigo_formatado', models.CharField(max_length=5)),
                ('titulo', models.CharField(max_length=500)),
                ('nota_explicativa', models.TextField()),
                ('direcao', models.CharField(choices=[('ENTRADA', 'entrada'), ('SAIDA', 'saída')], max_length=10)),
                ('alcance', models.CharField(choices=[('INTERNA', 'interno'), ('INTERESTADUAL', 'interestadual'), ('EXTERIOR', 'exterior')], max_length=20)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='fiscal.catalogocfop')),
            ],
            options={
                'verbose_name': 'item CFOP',
                'verbose_name_plural': 'itens CFOP',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogocfop',
            index=models.Index(fields=['ativo', 'referencia_em'], name='fiscal_cfop_ativo_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogocfop',
            constraint=models.UniqueConstraint(fields=('versao', 'fonte_sha256'), name='fiscal_cfop_versao_hash_uniq'),
        ),
        migrations.AddIndex(
            model_name='itemcfop',
            index=models.Index(fields=['codigo'], name='fiscal_cfop_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcfop',
            index=models.Index(fields=['direcao', 'alcance'], name='fiscal_cfop_dir_alc_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcfop',
            constraint=models.UniqueConstraint(fields=('catalogo', 'codigo'), name='fiscal_cfop_catalogo_codigo_uniq'),
        ),
    ]
