# Generated by Django 6.0.6 on 2026-09-09 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_cotacaocompra_chave_idempotencia'),
        ('fiscal', '0035_catalogocfop_itemcfop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RascunhoDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(default='supplier_return_draft_v1', editable=False, max_length=64)),
                ('chave_referenciada', models.CharField(max_length=44)),
                ('motivo_operacional', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Em preparação'), ('AGUARDANDO_REVISAO', 'Aguardando revisão fiscal'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=24)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rascunhos_devolucao_fornecedor_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rascunhos_devolucao_fornecedor_criados', to=settings.AUTH_USER_MODEL)),
                ('entrada_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rascunhos_devolucao_fornecedor', to='compras.entradacompra')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemRascunhoDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_recebida_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('item_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selecoes_devolucao_fornecedor', to='compras.itementradacompra')),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.rascunhodevolucaofornecedor')),
            ],
            options={
                'ordering': ['item_entrada_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rascunhodevolucaofornecedor',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RASCUNHO', 'AGUARDANDO_REVISAO'])), fields=('entrada_compra',), name='fisc_rasc_dev_entrada_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemrascunhodevolucaofornecedor',
            constraint=models.UniqueConstraint(fields=('rascunho', 'item_entrada'), name='fisc_item_rasc_dev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemrascunhodevolucaofornecedor',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='fisc_item_rasc_dev_qtd_pos'),
        ),
        migrations.AddConstraint(
            model_name='itemrascunhodevolucaofornecedor',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__lte', models.F('quantidade_recebida_snapshot'))), name='fisc_item_rasc_dev_qtd_lim'),
        ),
    ]
