# Generated by Django 6.0.6 on 2026-09-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0036_rascunhodevolucaofornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrascunhodevolucaofornecedor',
            name='item_xml_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='itemrascunhodevolucaofornecedor',
            name='numero_item_xml',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rascunhodevolucaofornecedor',
            name='submetido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rascunhodevolucaofornecedor',
            name='submetido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rascunhos_devolucao_fornecedor_submetidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rascunhodevolucaofornecedor',
            name='xml_origem_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='rascunhodevolucaofornecedor',
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(status='AGUARDANDO_REVISAO')
                    | (
                        models.Q(submetido_em__isnull=False)
                        & models.Q(submetido_por__isnull=False)
                        & ~models.Q(xml_origem_sha256='')
                    )
                ),
                name='fisc_rasc_dev_submissao_ok',
            ),
        ),
    ]
