# Generated by Django 6.0.6 on 2026-09-09 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_itementradacompra_numero_item_xml'),
        ('fiscal', '0037_itemrascunhodevolucaofornecedor_item_xml_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisaoDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(default='supplier_return_fiscal_review_v1', editable=False, max_length=64)),
                ('sequencia', models.PositiveIntegerField()),
                ('decisao', models.CharField(choices=[('APROVAR', 'Aprovar preparação'), ('DEVOLVER_CORRECAO', 'Devolver para correção')], max_length=24)),
                ('justificativa', models.CharField(max_length=500)),
                ('conteudo_snapshot', models.JSONField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rascunho_id', 'sequencia'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='rascunhodevolucaofornecedor',
            name='fisc_rasc_dev_entrada_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='rascunhodevolucaofornecedor',
            name='fisc_rasc_dev_submissao_ok',
        ),
        migrations.AlterField(
            model_name='rascunhodevolucaofornecedor',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Em preparação'), ('AGUARDANDO_REVISAO', 'Aguardando revisão fiscal'), ('APROVADO', 'Preparação aprovada'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='rascunhodevolucaofornecedor',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RASCUNHO', 'AGUARDANDO_REVISAO', 'APROVADO'])), fields=('entrada_compra',), name='fisc_rasc_dev_entrada_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rascunhodevolucaofornecedor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['AGUARDANDO_REVISAO', 'APROVADO']), _negated=True), models.Q(('submetido_em__isnull', False), ('submetido_por__isnull', False), models.Q(('xml_origem_sha256', ''), _negated=True)), _connector='OR'), name='fisc_rasc_dev_submissao_ok'),
        ),
        migrations.AddField(
            model_name='revisaodevolucaofornecedor',
            name='rascunho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to='fiscal.rascunhodevolucaofornecedor'),
        ),
        migrations.AddField(
            model_name='revisaodevolucaofornecedor',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_devolucao_fornecedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='revisaodevolucaofornecedor',
            constraint=models.UniqueConstraint(fields=('rascunho', 'sequencia'), name='fisc_rev_dev_rasc_seq_uniq'),
        ),
    ]
