# Generated by Django 6.0.6 on 2026-09-09 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0038_revisaodevolucaofornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParecerTributarioDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(default='supplier_return_tax_opinion_v1', editable=False, max_length=64)),
                ('versao', models.PositiveIntegerField()),
                ('vigencia_referencia', models.DateField()),
                ('regime_tributario_referencia', models.CharField(max_length=120)),
                ('natureza_operacao', models.CharField(max_length=120)),
                ('cfop', models.CharField(max_length=4)),
                ('tratamento_icms', models.TextField()),
                ('tratamento_icms_st_fcp', models.TextField()),
                ('tratamento_ipi', models.TextField()),
                ('tratamento_pis', models.TextField()),
                ('tratamento_cofins', models.TextField()),
                ('tratamento_cbenef', models.TextField()),
                ('tratamento_ibs_cbs', models.TextField()),
                ('fundamentacao', models.TextField()),
                ('conteudo_snapshot', models.JSONField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pareceres_tributarios', to='fiscal.rascunhodevolucaofornecedor')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pareceres_tributarios_devolucao_fornecedor', to=settings.AUTH_USER_MODEL)),
                ('revisao_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pareceres_tributarios', to='fiscal.revisaodevolucaofornecedor')),
            ],
            options={
                'ordering': ['rascunho_id', 'versao'],
                'constraints': [models.UniqueConstraint(fields=('rascunho', 'versao'), name='fisc_par_dev_rasc_vers_uniq'), models.UniqueConstraint(fields=('rascunho', 'conteudo_sha256'), name='fisc_par_dev_rasc_hash_uniq')],
            },
        ),
    ]
