# Generated by Django 6.0.6 on 2026-09-09 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0039_parecertributariodevolucaofornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrizacaoFiscalDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(default='supplier_return_item_tax_parameters_v1', editable=False, max_length=64)),
                ('versao', models.PositiveIntegerField()),
                ('conteudo_snapshot', models.JSONField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parecer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametrizacoes_fiscais', to='fiscal.parecertributariodevolucaofornecedor')),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametrizacoes_fiscais', to='fiscal.rascunhodevolucaofornecedor')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametrizacoes_fiscais_devolucao_fornecedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rascunho_id', 'versao'],
            },
        ),
        migrations.CreateModel(
            name='ItemParametrizacaoFiscalDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item_xml', models.CharField(max_length=10)),
                ('tipo_codigo_icms', models.CharField(choices=[('CST', 'CST'), ('CSOSN', 'CSOSN'), ('NAO_APLICAVEL', 'Não aplicável')], max_length=16)),
                ('origem_icms', models.CharField(max_length=1)),
                ('codigo_icms', models.CharField(blank=True, max_length=3)),
                ('codigo_ipi', models.CharField(max_length=2)),
                ('codigo_pis', models.CharField(max_length=2)),
                ('codigo_cofins', models.CharField(max_length=2)),
                ('codigo_cbenef', models.CharField(max_length=8)),
                ('tratamento_icms_st_fcp', models.TextField()),
                ('tratamento_cbenef', models.TextField()),
                ('tratamento_ibs_cbs', models.TextField()),
                ('observacao', models.TextField(blank=True)),
                ('item_rascunho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametrizacoes_fiscais', to='fiscal.itemrascunhodevolucaofornecedor')),
                ('parametrizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='fiscal.parametrizacaofiscaldevolucaofornecedor')),
            ],
            options={
                'ordering': ['item_rascunho_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='parametrizacaofiscaldevolucaofornecedor',
            constraint=models.UniqueConstraint(fields=('rascunho', 'versao'), name='fisc_param_dev_rasc_vers_uniq'),
        ),
        migrations.AddConstraint(
            model_name='parametrizacaofiscaldevolucaofornecedor',
            constraint=models.UniqueConstraint(fields=('rascunho', 'conteudo_sha256'), name='fisc_param_dev_rasc_hash_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemparametrizacaofiscaldevolucaofornecedor',
            constraint=models.UniqueConstraint(fields=('parametrizacao', 'item_rascunho'), name='fisc_item_param_dev_uniq'),
        ),
    ]
