# Generated by Django 6.0.6 on 2026-09-09 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0040_parametrizacaofiscaldevolucaofornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaCalculoDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(default='supplier_return_item_tax_calculation_memory_v1', editable=False, max_length=64)),
                ('versao', models.PositiveIntegerField()),
                ('criterio_arredondamento', models.CharField(max_length=500)),
                ('totais_snapshot', models.JSONField()),
                ('conteudo_snapshot', models.JSONField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parametrizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorias_calculo', to='fiscal.parametrizacaofiscaldevolucaofornecedor')),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorias_calculo', to='fiscal.rascunhodevolucaofornecedor')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorias_calculo_devolucao_fornecedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rascunho_id', 'versao'],
            },
        ),
        migrations.CreateModel(
            name='ItemMemoriaCalculoDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item_xml', models.CharField(max_length=10)),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_icms', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_icms', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valor_icms', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_icms_st', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_icms_st', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valor_icms_st', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_fcp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_fcp', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valor_fcp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_ipi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_ipi', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valor_ipi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_pis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_pis', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valor_pis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_cofins', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_cofins', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valor_cofins', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_ibs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_ibs', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valor_ibs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_cbs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_cbs', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valor_cbs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacao', models.TextField(blank=True)),
                ('item_parametrizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorias_calculo', to='fiscal.itemparametrizacaofiscaldevolucaofornecedor')),
                ('item_rascunho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorias_calculo', to='fiscal.itemrascunhodevolucaofornecedor')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='fiscal.memoriacalculodevolucaofornecedor')),
            ],
            options={
                'ordering': ['item_rascunho_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='memoriacalculodevolucaofornecedor',
            constraint=models.UniqueConstraint(fields=('rascunho', 'versao'), name='fisc_mem_dev_rasc_vers_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memoriacalculodevolucaofornecedor',
            constraint=models.UniqueConstraint(fields=('rascunho', 'conteudo_sha256'), name='fisc_mem_dev_rasc_hash_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itemmemoriacalculodevolucaofornecedor',
            constraint=models.UniqueConstraint(fields=('memoria', 'item_parametrizacao'), name='fisc_item_mem_dev_uniq'),
        ),
    ]
