# Generated by Django 6.0.6 on 2026-09-09 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0041_memoriacalculodevolucaofornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisaoMemoriaCalculoDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(default='supplier_return_item_tax_calculation_review_v1', editable=False, max_length=64)),
                ('decisao', models.CharField(choices=[('APROVAR', 'Aprovar memória'), ('DEVOLVER_CORRECAO', 'Devolver para correção')], max_length=24)),
                ('justificativa', models.CharField(max_length=500)),
                ('conteudo_snapshot', models.JSONField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('memoria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revisao_fiscal', to='fiscal.memoriacalculodevolucaofornecedor')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_memoria_calculo_devolucao_fornecedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['memoria__rascunho_id', 'memoria__versao'],
            },
        ),
    ]
