# Generated by Django 6.0.6 on 2026-09-09 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0042_revisaomemoriacalculodevolucaofornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('conteudo_snapshot', models.JSONField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='fiscal.memoriacalculodevolucaofornecedor')),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to='fiscal.rascunhodevolucaofornecedor')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['versao'],
                'constraints': [models.UniqueConstraint(fields=('rascunho', 'versao'), name='fisc_transp_dev_vers_uniq'), models.UniqueConstraint(fields=('rascunho', 'conteudo_sha256'), name='fisc_transp_dev_hash_uniq')],
            },
        ),
    ]
