# Generated by Django 6.0.6 on 2026-09-09 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0044_composicaodevolucaofornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisaoComposicaoDevolucaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('APROVAR', 'Composição aprovada'), ('DEVOLVER_CORRECAO', 'Devolvida para correção')], max_length=24)),
                ('conteudo_snapshot', models.JSONField()),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('composicao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revisao', to='fiscal.composicaodevolucaofornecedor')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
