# Generated by Django 6.0.6 on 2026-09-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0048_revisaoreflexosdevolucaofornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriacalculodevolucaofornecedor',
            name='reflexos_origem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memoria_revisada', to='fiscal.reflexosbasesdevolucaofornecedor'),
        ),
    ]
