# Generated by Django 6.0.6 on 2026-09-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0049_memoriacalculodevolucaofornecedor_reflexos_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriacalculodevolucaofornecedor',
            name='correcao_de',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memoria_corrigida', to='fiscal.memoriacalculodevolucaofornecedor'),
        ),
        migrations.AlterField(
            model_name='memoriacalculodevolucaofornecedor',
            name='reflexos_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memoria_revisada', to='fiscal.reflexosbasesdevolucaofornecedor'),
        ),
    ]
