# Generated by Django 6.0.6 on 2026-09-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0053_documentofiscal_reserva_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaHomologacaoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('DESATIVADO', 'Emissão externa desativada'), ('PADRAO_SERVIDOR', 'Compatibilidade do servidor'), ('FOCUS', 'Integração Focus NFe'), ('SEFAZ_DIRETA_GO', 'Conexão direta SEFAZ - Goiás')], max_length=24)),
                ('operacao', models.CharField(choices=[('AUTORIZACAO', 'Autorização'), ('CONSULTA', 'Consulta'), ('REJEICAO', 'Rejeição controlada'), ('CANCELAMENTO', 'Cancelamento'), ('INUTILIZACAO', 'Inutilização'), ('EVENTOS', 'Eventos'), ('DFE', 'Distribuição DF-e')], max_length=24)),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologacao'), ('PRODUCAO', 'Producao')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de revisão'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=16)),
                ('referencia', models.CharField(help_text='Referência protegida do chamado, pacote, protocolo ou cofre de evidências.', max_length=500)),
                ('conteudo_sha256', models.CharField(help_text='SHA-256 do pacote de evidências, sem armazenar segredo neste registro.', max_length=64)),
                ('codigo_status', models.CharField(blank=True, max_length=20)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('versao_aplicacao', models.CharField(max_length=80)),
                ('resultado_esperado', models.TextField()),
                ('resultado_obtido', models.TextField()),
                ('observacoes_revisao', models.TextField(blank=True)),
                ('registrada_em', models.DateTimeField(auto_now_add=True)),
                ('revisada_em', models.DateTimeField(blank=True, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_homologacao_canal', to='fiscal.configuracaofiscal')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_homologacao_registradas', to=settings.AUTH_USER_MODEL)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_homologacao_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evidência de homologação por canal',
                'verbose_name_plural': 'evidências de homologação por canal',
                'ordering': ['-registrada_em', '-id'],
                'indexes': [models.Index(fields=['configuracao', 'canal', 'operacao', 'status'], name='fiscal_ev_hom_canal_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ambiente', 'HOMOLOGACAO')), name='fiscal_ev_hom_apenas_homologacao'), models.CheckConstraint(condition=models.Q(models.Q(('revisada_em__isnull', True), ('revisada_por__isnull', True), ('status', 'PENDENTE')), models.Q(('status__in', ['APROVADA', 'REJEITADA']), ('revisada_por__isnull', False), ('revisada_em__isnull', False)), _connector='OR'), name='fiscal_ev_hom_revisao_coerente')],
            },
        ),
    ]
