# Generated by Django 6.0.6 on 2026-09-18 17:58

import base64
import hashlib

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _fernet():
    digest = hashlib.sha256(settings.FISCAL_CERTIFICATE_KEY.encode("utf-8")).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


def criptografar_csc_existente(apps, schema_editor):
    ConfiguracaoFiscal = apps.get_model("fiscal", "ConfiguracaoFiscal")
    agora = timezone.now()
    for configuracao in ConfiguracaoFiscal.objects.exclude(csc_token="").iterator():
        configuracao.csc_token_criptografado = _fernet().encrypt(
            configuracao.csc_token.encode("utf-8")
        )
        configuracao.csc_token_atualizado_em = agora
        configuracao.save(
            update_fields=["csc_token_criptografado", "csc_token_atualizado_em"]
        )


def restaurar_csc_legado(apps, schema_editor):
    ConfiguracaoFiscal = apps.get_model("fiscal", "ConfiguracaoFiscal")
    for configuracao in ConfiguracaoFiscal.objects.exclude(
        csc_token_criptografado__isnull=True
    ).iterator():
        configuracao.csc_token = _fernet().decrypt(
            bytes(configuracao.csc_token_criptografado)
        ).decode("utf-8")
        configuracao.save(update_fields=["csc_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0054_evidenciahomologacaocanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='csc_token_atualizado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='csc_token_criptografado',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.RunPython(
            criptografar_csc_existente,
            restaurar_csc_legado,
        ),
        migrations.RemoveField(
            model_name='configuracaofiscal',
            name='csc_token',
        ),
    ]
