# Generated by Django 6.0.6 on 2026-09-21 12:24

from django.conf import settings
from django.db import migrations, models


def validar_origens_nao_simultaneas(apps, schema_editor):
    DocumentoFiscal = apps.get_model("fiscal", "DocumentoFiscal")
    ids = list(
        DocumentoFiscal.objects.filter(
            venda_id__isnull=False,
            pedido_online_id__isnull=False,
        ).values_list("id", flat=True)[:50]
    )
    if ids:
        raise RuntimeError(
            "Existem documentos fiscais ligados simultaneamente a venda e pedido online. "
            f"IDs: {ids}. Classifique as origens antes de aplicar a migration 0056."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('fiscal', '0055_protege_csc_criptografado'),
        ('marketplace', '0011_pedidoonline_destinatario_bairro_and_more'),
        ('vendas', '0012_alter_venda_documento_consumidor_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validar_origens_nao_simultaneas,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.CheckConstraint(condition=models.Q(('venda__isnull', True), ('pedido_online__isnull', True), _connector='OR'), name='fisc_doc_origens_nao_simultaneas'),
        ),
    ]
