# Generated by Django 6.0.6 on 2026-09-21 12:47

from django.conf import settings
from django.db import migrations, models


def validar_exatamente_uma_origem(apps, schema_editor):
    DocumentoFiscal = apps.get_model("fiscal", "DocumentoFiscal")
    sem_origem = list(
        DocumentoFiscal.objects.filter(
            venda_id__isnull=True,
            pedido_online_id__isnull=True,
        ).values_list("id", flat=True)[:50]
    )
    dupla_origem = list(
        DocumentoFiscal.objects.filter(
            venda_id__isnull=False,
            pedido_online_id__isnull=False,
        ).values_list("id", flat=True)[:50]
    )
    if sem_origem or dupla_origem:
        raise RuntimeError(
            "Existem documentos fiscais incompatíveis com a origem obrigatória. "
            f"Sem origem: {sem_origem or 'nenhum'}; "
            f"venda e pedido simultâneos: {dupla_origem or 'nenhum'}. "
            "Classifique os registros com evidência antes de aplicar a migration 0057; "
            "nenhum vínculo será inferido e nenhum documento será apagado automaticamente."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_bloquear_finalizacao_entrada_divergente'),
        ('fiscal', '0056_bloqueia_origens_simultaneas_documento'),
        ('marketplace', '0011_pedidoonline_destinatario_bairro_and_more'),
        ('vendas', '0012_alter_venda_documento_consumidor_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validar_exatamente_uma_origem,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='documentofiscal',
            name='fisc_doc_origens_nao_simultaneas',
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pedido_online__isnull', True), ('venda__isnull', False)), models.Q(('pedido_online__isnull', False), ('venda__isnull', True)), _connector='OR'), name='fisc_doc_exatamente_uma_origem'),
        ),
    ]
