# Generated by Django 6.0.6 on 2026-09-21 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0057_exige_origem_documento_fiscal'),
        ('produtos', '0015_versaoprecoproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrizacaoBeneficioFiscalProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('INDEFINIDO', 'Ainda não definido'), ('SEM_BENEFICIO', 'Sem benefício fiscal'), ('COM_BENEFICIO', 'Com benefício fiscal')], default='INDEFINIDO', help_text='Definição contábil explícita para este produto nesta operação.', max_length=20, verbose_name='Situação do benefício de ICMS')),
                ('codigo_beneficio_fiscal', models.CharField(blank=True, help_text='Use o código oficial aplicável ou SEM CBENEF quando previsto no catálogo estadual.', max_length=10, verbose_name='Código de benefício fiscal (cBenef)')),
                ('fundamento_contabil', models.TextField(blank=True, help_text='Referência da orientação usada; não informe credenciais ou dados financeiros.', verbose_name='Fundamento/orientação contábil')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametrizacoes_beneficio_fiscal_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('natureza_operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametrizacoes_beneficio_fiscal', to='fiscal.naturezaoperacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametrizacoes_beneficio_fiscal', to='produtos.produto')),
            ],
            options={
                'ordering': ['natureza_operacao__descricao', 'produto__nome'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'natureza_operacao'), name='fisc_benef_produto_natureza_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('codigo_beneficio_fiscal', ''), ('situacao', 'INDEFINIDO')), models.Q(('codigo_beneficio_fiscal__in', ['', 'SEM CBENEF']), ('situacao', 'SEM_BENEFICIO')), models.Q(('situacao', 'COM_BENEFICIO'), models.Q(('codigo_beneficio_fiscal__in', ['', 'SEM CBENEF']), _negated=True)), _connector='OR'), name='fisc_benef_situacao_codigo_coerente')],
            },
        ),
    ]
