# Generated by Django 6.0.6 on 2026-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0058_parametrizacaobeneficiofiscalproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrizacaobeneficiofiscalproduto',
            name='cfop',
            field=models.CharField(blank=True, help_text='Se vazio, será utilizado o CFOP padrão da natureza.', max_length=4, verbose_name='CFOP específico'),
        ),
    ]
