# Generated by Django 6.0.6 on 2026-07-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_documentofiscalsincronizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoentradasincronizacao',
            name='resolucao_conflito',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventoentradasincronizacao',
            name='resolvido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoentradasincronizacao',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_entrada_resolvidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoentradasincronizacao',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('CONFLITO', 'Conflito'), ('ERRO', 'Erro'), ('RESOLVIDO', 'Resolvido manualmente')], default='RECEBIDO', max_length=20),
        ),
    ]
