# Generated by Django 6.0.6 on 2026-07-06 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_eventoentradasincronizacao_resolucao_conflito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='Envie uma imagem PNG, JPG ou JPEG.')]),
        ),
    ]
