# Generated by Django 6.0.6 on 2026-07-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='politica_conflito_sincronizacao',
            field=models.CharField(choices=[('MANUAL', 'Resolver manualmente'), ('REMOTO_PRODUTOS_ESTOQUE', 'Nuvem prevalece para produtos e estoque')], default='MANUAL', max_length=40, verbose_name='Politica de conflito'),
        ),
    ]
