# Generated by Django 6.0.6 on 2026-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_alter_empresa_politica_conflito_sincronizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoentradasincronizacao',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('CONFLITO', 'Conflito'), ('ERRO', 'Erro'), ('RESOLVIDO', 'Resolvido manualmente'), ('PAUSADO', 'Pausado pela política')], default='RECEBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventosincronizacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro'), ('PAUSADO', 'Pausado pela política')], default='PENDENTE', max_length=20),
        ),
    ]
