# Generated by Django 6.0.6 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_alter_eventoentradasincronizacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='politica_conflito_sincronizacao',
            field=models.CharField(choices=[('MANUAL', 'Resolver manualmente'), ('REMOTO_PRODUTOS_ESTOQUE', 'Nuvem prevalece para produtos e estoque'), ('LOCAL_PRODUTOS_ESTOQUE', 'Loja prevalece para produtos e estoque')], default='MANUAL', max_length=40, verbose_name='Política de conflito'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sincronizacao_automatica',
            field=models.BooleanField(default=False, verbose_name='Sincronizacao automática'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, max_length=7, verbose_name='Código município IBGE'),
        ),
    ]
