# Generated by Django 6.0.6 on 2026-07-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_alter_empresa_politica_conflito_sincronizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='modo_implantacao',
            field=models.CharField(choices=[('LOCAL', 'Somente servidor local'), ('HIBRIDO', 'Servidor local com sincronização em nuvem'), ('NUVEM_AGENTE', 'Nuvem com agente local')], default='LOCAL', max_length=20, verbose_name='Modo de implantacao'),
        ),
    ]
