# Generated by Django 6.0.6 on 2026-08-03 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_alter_empresa_modo_implantacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiroSincronizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lancamento_externo_id', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=20)),
                ('origem', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField()),
                ('conta_movimento', models.CharField(blank=True, max_length=160)),
                ('centro_custo', models.CharField(blank=True, max_length=180)),
                ('conta_contabil', models.CharField(blank=True, max_length=220)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('estorno_de_externo_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros_sincronizados', to='empresas.empresa')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lancamento_financeiro_sincronizado', to='empresas.eventoentradasincronizacao')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros_sincronizados', to='empresas.filial')),
            ],
            options={
                'ordering': ['-data', '-recebido_em'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'lancamento_externo_id'), name='empresas_lanc_fin_sync_unico')],
            },
        ),
    ]
