# Generated by Django 6.0.6 on 2026-08-04 13:00

import apps.empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_lancamentofinanceirosincronizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='acoes_credencial_exigem_pin',
            field=models.JSONField(blank=True, default=apps.empresas.models.acoes_pin_supervisor_padrao, verbose_name='Ações que exigem cartão e PIN'),
        ),
    ]
