# Generated by Django 6.0.6 on 2026-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_empresa_acoes_credencial_exigem_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='filial',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='filial',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='filial',
            name='complemento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='filial',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='filial',
            name='numero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço completo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modo_implantacao',
            field=models.CharField(choices=[('LOCAL', 'Somente servidor local'), ('HIBRIDO', 'Servidor local com sincronização em nuvem'), ('NUVEM_AGENTE', 'Nuvem com agente local')], default='LOCAL', max_length=20, verbose_name='Modo de implantação'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=255, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='regime_tributario',
            field=models.CharField(blank=True, max_length=80, verbose_name='Regime tributário'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, max_length=7, verbose_name='Código do município no IBGE'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço completo'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='municipio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
    ]
