# Generated by Django 6.0.6 on 2026-08-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_empresa_bairro_empresa_cep_empresa_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='sincronizacao_automatica',
            field=models.BooleanField(default=False, verbose_name='Sincronização automática'),
        ),
    ]
