# Generated by Django 6.0.6 on 2026-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_criar_filiais_matriz_ausentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bloquear_finalizacao_entrada_divergente',
            field=models.BooleanField(default=True, help_text='Mantém estoque e financeiro protegidos até a conferência física registrada.', verbose_name='Bloquear finalização de entrada divergente sem conferência física'),
        ),
    ]
