# Generated by Django 6.0.6 on 2026-06-25 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, max_length=80)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('total_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to='empresas.filial')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to='fornecedores.fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntradaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('atualizar_preco_custo', models.BooleanField(default=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.entradacompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='produtos.produto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
