# Generated by Django 6.0.6 on 2026-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradacompra',
            name='gerar_conta_financeira',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='vencimento_financeiro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
