# Generated by Django 6.0.6 on 2026-07-25

import decimal
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_entradacompra_gerar_conta_financeira_and_more"),
        ("empresas", "0011_empresa_politica_conflito_sincronizacao"),
        ("fornecedores", "0001_initial"),
        ("produtos", "0004_alter_produto_imagem_alter_produtoimagem_imagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("referencia", models.CharField(blank=True, max_length=80)),
                ("previsao_entrega", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("ENVIADO", "Enviado ao fornecedor"), ("CANCELADO", "Cancelado")], default="RASCUNHO", max_length=20)),
                ("total_previsto", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filial", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pedidos_compra", to="empresas.filial")),
                ("fornecedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pedidos_compra", to="fornecedores.fornecedor")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pedidos_compra", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ItemPedidoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.001"))])),
                ("custo_unitario_previsto", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ("total_previsto", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("pedido", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="compras.pedidocompra")),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="itens_pedido_compra", to="produtos.produto")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="itempedidocompra",
            constraint=models.UniqueConstraint(fields=("pedido", "produto"), name="compras_pedido_produto_unico"),
        ),
    ]
