# Generated by Django 6.0.6 on 2026-07-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_pedidocompra_itempedidocompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="entradacompra",
            name="pedido_origem",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entrada_gerada",
                to="compras.pedidocompra",
            ),
        ),
        migrations.AlterField(
            model_name="pedidocompra",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("ENVIADO", "Enviado ao fornecedor"),
                    ("CONVERTIDO", "Entrada de compra gerada"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="RASCUNHO",
                max_length=20,
            ),
        ),
    ]
