# Generated by Django 6.0.6 on 2026-07-25

import decimal
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0004_entradacompra_pedido_origem_e_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CotacaoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("referencia", models.CharField(blank=True, max_length=80)),
                ("validade", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("ABERTA", "Aberta para propostas"), ("ENCERRADA", "Encerrada com pedido"), ("CANCELADA", "Cancelada")], default="RASCUNHO", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filial", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cotacoes_compra", to="empresas.filial")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cotacoes_compra", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ItemCotacaoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.001"))])),
                ("cotacao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="compras.cotacaocompra")),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="itens_cotacao_compra", to="produtos.produto")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="RespostaCotacaoFornecedor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prazo_entrega_dias", models.PositiveIntegerField(default=0)),
                ("observacoes", models.TextField(blank=True)),
                ("selecionada", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cotacao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="respostas", to="compras.cotacaocompra")),
                ("fornecedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="respostas_cotacao", to="fornecedores.fornecedor")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="respostas_cotacao", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["fornecedor__razao_social"]},
        ),
        migrations.CreateModel(
            name="PrecoRespostaCotacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("disponivel", models.BooleanField(default=True)),
                ("custo_unitario", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="precos_fornecedores", to="compras.itemcotacaocompra")),
                ("resposta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="precos", to="compras.respostacotacaofornecedor")),
            ],
            options={"ordering": ["item_id"]},
        ),
        migrations.AddField(
            model_name="pedidocompra",
            name="cotacao_origem",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="pedido_gerado", to="compras.cotacaocompra"),
        ),
        migrations.AddConstraint(
            model_name="itemcotacaocompra",
            constraint=models.UniqueConstraint(fields=("cotacao", "produto"), name="compras_cotacao_produto_unico"),
        ),
        migrations.AddConstraint(
            model_name="respostacotacaofornecedor",
            constraint=models.UniqueConstraint(fields=("cotacao", "fornecedor"), name="compras_cotacao_fornecedor_unico"),
        ),
        migrations.AddConstraint(
            model_name="precorespostacotacao",
            constraint=models.UniqueConstraint(fields=("resposta", "item"), name="compras_resposta_item_unico"),
        ),
    ]
