# Generated by Django 6.0.6 on 2026-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_itementradacompra_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradacompra',
            name='conferencia_resumo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='conferencia_status',
            field=models.CharField(choices=[('NAO_APLICAVEL', 'Sem pedido vinculado'), ('PENDENTE', 'Aguardando XML'), ('CONFERIDA', 'Conferida'), ('DIVERGENTE', 'Divergente')], default='NAO_APLICAVEL', max_length=20),
        ),
    ]
