# Generated by Django 6.0.6 on 2026-08-17 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_entradacompra_conferencia_resumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entradacompra',
            name='conferencia_fisica_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='conferencia_fisica_observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entradacompra',
            name='conferencia_fisica_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_fisicas_compra', to=settings.AUTH_USER_MODEL),
        ),
    ]
