# Generated by Django 6.0.6 on 2026-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_entradacompra_conferencia_fisica_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaocompra',
            name='chave_idempotencia',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
