# Generated by Django 6.0.6 on 2026-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_cotacaocompra_chave_idempotencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementradacompra',
            name='numero_item_xml',
            field=models.CharField(blank=True, help_text='nItem preservado quando a entrada foi importada de NF-e.', max_length=10, verbose_name='Item no XML de origem'),
        ),
    ]
