# Generated by Django 6.0.6 on 2026-09-18 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_itementradacompra_numero_item_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaNFeEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=60)),
                ('valor_original', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_nfe', to='compras.entradacompra')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicataNFeEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveSmallIntegerField()),
                ('numero', models.CharField(max_length=60)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=13)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicatas', to='compras.faturanfeentrada')),
            ],
            options={
                'ordering': ['sequencia'],
                'constraints': [models.UniqueConstraint(fields=('fatura', 'sequencia'), name='compras_dup_nfe_fatura_seq_uniq'), models.UniqueConstraint(fields=('fatura', 'numero'), name='compras_dup_nfe_fatura_num_uniq'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='compras_dup_nfe_valor_positivo')],
            },
        ),
    ]
