# Generated by Django 6.0.6 on 2026-09-28 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_faturanfeentrada_duplicatanfeentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itementradacompra',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='custo_unitario_previsto',
            field=models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='precorespostacotacao',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
