# Generated by Django 6.0.6 on 2026-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_alter_itementradacompra_custo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementradacompra',
            name='origem_xml_snapshot',
            field=models.JSONField(blank=True, help_text='Dados documentais e conversão de unidade aplicados na importação da NF-e.', null=True, verbose_name='Evidência da origem XML'),
        ),
    ]
