"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_path(name, default):
    raw = os.getenv(name)
    path = Path(raw) if raw else Path(default)
    return path if path.is_absolute() else BASE_DIR / path


def env_json_object(name, default="{}"):
    raw = os.getenv(name, default)
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ImproperlyConfigured(f"{name} deve conter um objeto JSON valido.") from exc
    if not isinstance(value, dict):
        raise ImproperlyConfigured(f"{name} deve conter um objeto JSON.")
    return value


ENVIRONMENT = os.getenv("DJANGO_ENV", "development")

SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-dev-supermercado")
DEBUG = env_bool("DEBUG", ENVIRONMENT != "production")

if not DEBUG and SECRET_KEY == "django-insecure-dev-supermercado":
    raise ImproperlyConfigured("Defina SECRET_KEY no ambiente antes de rodar fora do modo DEBUG.")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "127.0.0.1,localhost")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
CSRF_FAILURE_VIEW = "config.views.csrf_failure"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.accounts',
    'apps.empresas',
    'apps.produtos',
    'apps.clientes',
    'apps.fornecedores',
    'apps.compras',
    'apps.estoque',
    'apps.promocoes',
    'apps.pdv',
    'apps.vendas',
    'apps.financeiro',
    'apps.fiscal',
    'apps.marketplace',
    'apps.relatorios',
    'apps.auditoria',
    'apps.configuracoes',
    'apps.licenciamento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.licenciamento.middleware.ControleLicencaMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                'apps.configuracoes.templatetags.formatadores',
            ],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.accounts.context_processors.supermarket_access',
                'apps.licenciamento.context_processors.alerta_licenciamento',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv("DATABASE_URL") or os.getenv("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "supermercado"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.getenv("POSTGRES_CONN_MAX_AGE", "60")),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': env_path("SQLITE_PATH", BASE_DIR / 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = env_path("STATIC_ROOT", BASE_DIR / 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = env_path("MEDIA_ROOT", BASE_DIR / 'media')

SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0" if DEBUG else "31536000"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if env_bool("USE_X_FORWARDED_PROTO", False) else None
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'relatorios:dashboard'
LOGOUT_REDIRECT_URL = 'login'

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "nao-responda@supermercado.local")

PDV_NUVEM_REQUER_APROVACAO = env_bool("PDV_NUVEM_REQUER_APROVACAO", False)
PDV_DESKTOP_VERSION = os.getenv("PDV_DESKTOP_VERSION", "0.1.9")
PDV_DESKTOP_MIN_VERSION = os.getenv("PDV_DESKTOP_MIN_VERSION", PDV_DESKTOP_VERSION)
PDV_DESKTOP_RELEASE_CHANNEL = os.getenv("PDV_DESKTOP_RELEASE_CHANNEL", "ESTAVEL").upper()
# A simulacao TEF precisa ser uma escolha explicita ate em desenvolvimento.
# Assim, um terminal sem adquirente configurada nunca aprova pagamento por acaso.
PDV_TEF_SIMULATOR_ENABLED = env_bool("PDV_TEF_SIMULATOR_ENABLED", False)
PDV_DESKTOP_INSTALLER_PATH = env_path("PDV_DESKTOP_INSTALLER_PATH", BASE_DIR / "artifacts" / "DeTecPDV.exe")
PDV_DESKTOP_REQUIRE_SIGNED_INSTALLER = env_bool("PDV_DESKTOP_REQUIRE_SIGNED_INSTALLER", not DEBUG)
LOCAL_SERVER_VERSION = os.getenv("LOCAL_SERVER_VERSION", "0.1.0")
LOCAL_SERVER_PACKAGE_PATH = env_path("LOCAL_SERVER_PACKAGE_PATH", BASE_DIR / "artifacts" / "DeigoVarejoServidorLocal.zip")
LOCAL_SERVER_OFFLINE_PACKAGE_PATH = env_path("LOCAL_SERVER_OFFLINE_PACKAGE_PATH", BASE_DIR / "artifacts" / "DeTecServerOffline.zip")
LOCAL_SERVER_REQUIRE_SIGNED_COMMIT = env_bool("LOCAL_SERVER_REQUIRE_SIGNED_COMMIT", not DEBUG)
FISCAL_CERTIFICATE_KEY = os.getenv("FISCAL_CERTIFICATE_KEY", SECRET_KEY)
FISCAL_SEFAZ_ADAPTER = os.getenv("FISCAL_SEFAZ_ADAPTER", "")
FINANCEIRO_CONTABIL_ADAPTER = os.getenv("FINANCEIRO_CONTABIL_ADAPTER", "")
FISCAL_SCHEMA_DIR = env_path("FISCAL_SCHEMA_DIR", BASE_DIR / "fiscal_schemas")
FISCAL_NFE_SCHEMA_FILE = os.getenv("FISCAL_NFE_SCHEMA_FILE", "nfe_v4.00.xsd")
FISCAL_SCHEMA_SHA256 = os.getenv("FISCAL_SCHEMA_SHA256", "")
FISCAL_LOCAL_XML_SIGNATURE_ENABLED = env_bool("FISCAL_LOCAL_XML_SIGNATURE_ENABLED", True)
FISCAL_AUTO_TRANSMIT_ENABLED = env_bool("FISCAL_AUTO_TRANSMIT_ENABLED", False)
FISCAL_AUTO_TRANSMIT_MAX_ATTEMPTS = int(os.getenv("FISCAL_AUTO_TRANSMIT_MAX_ATTEMPTS", "8"))
FISCAL_AUTO_QUERY_MAX_ATTEMPTS = int(os.getenv("FISCAL_AUTO_QUERY_MAX_ATTEMPTS", "12"))
FISCAL_AUTO_TRANSMIT_RETRY_BASE_SECONDS = int(os.getenv("FISCAL_AUTO_TRANSMIT_RETRY_BASE_SECONDS", "60"))
FISCAL_AUTO_TRANSMIT_RETRY_MAX_SECONDS = int(os.getenv("FISCAL_AUTO_TRANSMIT_RETRY_MAX_SECONDS", "3600"))
FISCAL_AUTO_TRANSMIT_LEASE_SECONDS = int(os.getenv("FISCAL_AUTO_TRANSMIT_LEASE_SECONDS", "300"))
SINCRONIZACAO_API_TOKEN = os.getenv("SINCRONIZACAO_API_TOKEN", "")
SINCRONIZACAO_TOKENS_EMPRESA = env_json_object("SINCRONIZACAO_TOKENS_EMPRESA_JSON")
SINCRONIZACAO_PERMITE_TOKEN_GLOBAL = env_bool("SINCRONIZACAO_PERMITE_TOKEN_GLOBAL", False)
SINCRONIZACAO_MAX_EVENTO_BYTES = int(os.getenv("SINCRONIZACAO_MAX_EVENTO_BYTES", str(1024 * 1024)))
SINCRONIZACAO_TIMEOUT_SEGUNDOS = int(os.getenv("SINCRONIZACAO_TIMEOUT_SEGUNDOS", "10"))
SINCRONIZACAO_MAX_TENTATIVAS = int(os.getenv("SINCRONIZACAO_MAX_TENTATIVAS", "8"))
SINCRONIZACAO_RETRY_BASE_SEGUNDOS = int(os.getenv("SINCRONIZACAO_RETRY_BASE_SEGUNDOS", "30"))
SINCRONIZACAO_RETRY_MAX_SEGUNDOS = int(os.getenv("SINCRONIZACAO_RETRY_MAX_SEGUNDOS", "3600"))
LICENCIAMENTO_CENTRAL_URL = os.getenv("LICENCIAMENTO_CENTRAL_URL", "")
LICENCIAMENTO_API_TOKEN = os.getenv("LICENCIAMENTO_API_TOKEN", "")
LICENCIAMENTO_INSTALACAO_ID = os.getenv("LICENCIAMENTO_INSTALACAO_ID", "")
LICENCIAMENTO_CHAVE_ASSINATURA = os.getenv("LICENCIAMENTO_CHAVE_ASSINATURA", SECRET_KEY)
LICENCIAMENTO_CONCESSAO_HORAS = int(os.getenv("LICENCIAMENTO_CONCESSAO_HORAS", "24"))
LICENCIAMENTO_OFFLINE_DIAS = int(os.getenv("LICENCIAMENTO_OFFLINE_DIAS", "3"))
LICENCIAMENTO_TIMEOUT_SEGUNDOS = int(os.getenv("LICENCIAMENTO_TIMEOUT_SEGUNDOS", "10"))
LICENCIAMENTO_CHAVE_PRIVADA_PEM = os.getenv("LICENCIAMENTO_CHAVE_PRIVADA_PEM", "")
LICENCIAMENTO_CHAVE_PRIVADA_ARQUIVO = os.getenv("LICENCIAMENTO_CHAVE_PRIVADA_ARQUIVO", "")
LICENCIAMENTO_CHAVE_PUBLICA_PEM = os.getenv("LICENCIAMENTO_CHAVE_PUBLICA_PEM", "")
LICENCIAMENTO_CHAVE_PUBLICA_ARQUIVO = os.getenv("LICENCIAMENTO_CHAVE_PUBLICA_ARQUIVO", "")
LICENCIAMENTO_PERMITIR_ASSINATURA_COMPARTILHADA = env_bool("LICENCIAMENTO_PERMITIR_ASSINATURA_COMPARTILHADA", DEBUG)
ASAAS_API_URL = os.getenv("ASAAS_API_URL", "https://api-sandbox.asaas.com/v3")
ASAAS_API_KEY = os.getenv("ASAAS_API_KEY", "")
ASAAS_WEBHOOK_TOKEN = os.getenv("ASAAS_WEBHOOK_TOKEN", "")
ASAAS_TIMEOUT_SEGUNDOS = int(os.getenv("ASAAS_TIMEOUT_SEGUNDOS", "15"))
CADASTRO_CNPJ_PROVIDER_URL = os.getenv("CADASTRO_CNPJ_PROVIDER_URL", "")
CADASTRO_CEP_PROVIDER_URL = os.getenv("CADASTRO_CEP_PROVIDER_URL", "")
CADASTRO_LOOKUP_TIMEOUT_SEGUNDOS = int(os.getenv("CADASTRO_LOOKUP_TIMEOUT_SEGUNDOS", "5"))
MARKETPLACE_PARTNER_ADAPTERS = env_json_object("MARKETPLACE_PARTNER_ADAPTERS_JSON")
MARKETPLACE_GEOCODING_PROVIDER_URL = os.getenv("MARKETPLACE_GEOCODING_PROVIDER_URL", "")
MARKETPLACE_GEOCODING_TIMEOUT_SEGUNDOS = int(os.getenv("MARKETPLACE_GEOCODING_TIMEOUT_SEGUNDOS", "5"))

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOG_DIR = env_path("LOG_DIR", BASE_DIR / "logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "padrao": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "padrao",
        },
        "arquivo": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "supermercado.log",
            "maxBytes": int(os.getenv("LOG_MAX_BYTES", "10485760")),
            "backupCount": int(os.getenv("LOG_BACKUP_COUNT", "5")),
            "formatter": "padrao",
            "encoding": "utf-8",
        },
    },
    "root": {
        "handlers": ["console", "arquivo"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.security": {
            "handlers": ["console", "arquivo"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

ADMIN_DESKTOP_VERSION = os.getenv('ADMIN_DESKTOP_VERSION', '0.1.0')
ADMIN_DESKTOP_INSTALLER_PATH = env_path('ADMIN_DESKTOP_INSTALLER_PATH', BASE_DIR / 'artifacts' / 'DeTecAdmin.exe')
