from django.urls import path

from . import views

app_name = "configuracoes"

urlpatterns = [
    path("", views.painel_sistema, name="painel"),
    path("super-admin/", views.super_admin, name="super_admin"),
    path("super-admin/diagnostico.json", views.super_admin_diagnostico, name="super_admin_diagnostico"),
    path("super-admin/diagnostico.csv", views.super_admin_diagnostico_csv, name="super_admin_diagnostico_csv"),
    path("super-admin/modelos/<str:app_label>/<str:model_name>/", views.super_admin_modelo, name="super_admin_modelo"),
    path("checklist/", views.checklist_projeto, name="checklist"),
    path("homologacao-operacional/", views.homologacao_operacional, name="homologacao_operacional"),
    path("checklist/exportar.csv", views.checklist_projeto_csv, name="checklist_csv"),
    path("backup/", views.backup_operacional, name="backup"),
    path("backup/download/", views.backup_download, name="backup_download"),
    path("pdv-desktop/", views.pdv_desktop, name="pdv_desktop"),
    path("pdv-desktop/download/windows/", views.pdv_desktop_download_windows, name="pdv_desktop_download_windows"),
    path("pdv-desktop/manifest.json", views.pdv_desktop_manifest, name="pdv_desktop_manifest"),
    path("pdv-desktop/terminais/<int:pk>/pacote.json", views.pdv_desktop_terminal_pacote, name="pdv_desktop_terminal_pacote"),
    path("admin-desktop/", views.admin_desktop, name="admin_desktop"),
    path("admin-desktop/download/windows/", views.admin_desktop_download_windows, name="admin_desktop_download_windows"),
    path("servidor-local/", views.servidor_local, name="servidor_local"),
    path("servidor-local/manifest.json", views.servidor_local_manifest, name="servidor_local_manifest"),
    path("servidor-local/piloto/previa.json", views.servidor_local_previa_piloto, name="servidor_local_previa_piloto"),
    path("servidor-local/piloto/ficha.json", views.servidor_local_ficha_piloto, name="servidor_local_ficha_piloto"),
    path("servidor-local/piloto/relatorio.json", views.servidor_local_relatorio_piloto, name="servidor_local_relatorio_piloto"),
    path("servidor-local/piloto/verificar-arquivos.json", views.servidor_local_verificar_artefatos_piloto, name="servidor_local_verificar_artefatos_piloto"),
    path("servidor-local/piloto/dossie.zip", views.servidor_local_dossie_piloto, name="servidor_local_dossie_piloto"),
    path("servidor-local/piloto/verificar-dossie.json", views.servidor_local_verificar_dossie_piloto, name="servidor_local_verificar_dossie_piloto"),
    path("servidor-local/download/", views.servidor_local_download, name="servidor_local_download"),
    path("servidor-local/offline/download/", views.servidor_local_offline_download, name="servidor_local_offline_download"),
    path("servidor-local/evidencias.zip", views.servidor_local_evidencias, name="servidor_local_evidencias"),
    path("formas-pagamento/", views.formas_pagamento, name="formas_pagamento"),
    path("formas-pagamento/nova/", views.forma_pagamento_form, name="forma_pagamento_nova"),
    path("formas-pagamento/<int:pk>/editar/", views.forma_pagamento_form, name="forma_pagamento_editar"),
    path("terminais-pdv/", views.terminais_pdv, name="terminais_pdv"),
    path("terminais-pdv/diagnosticos/", views.terminais_pdv_diagnosticos, name="terminais_pdv_diagnosticos"),
    path("terminais-pdv/diagnosticos/exportar.csv", views.terminais_pdv_diagnosticos_csv, name="terminais_pdv_diagnosticos_csv"),
    path("terminais-pdv/novo/", views.terminal_pdv_form, name="terminal_pdv_novo"),
    path("terminais-pdv/<int:pk>/editar/", views.terminal_pdv_form, name="terminal_pdv_editar"),
    path("terminais-pdv/<int:pk>/licenca/<str:acao>/", views.terminal_pdv_alterar_licenca, name="terminal_pdv_alterar_licenca"),
    path("terminais-pdv/<int:pk>/regenerar-chave/", views.terminal_pdv_regenerar_chave, name="terminal_pdv_regenerar_chave"),
    path("impressoes/", views.impressoes, name="impressoes"),
    path("impressoes/impressoras-locais.json", views.impressoras_locais, name="impressoras_locais"),
    path("impressoes/desktop.json", views.impressoes_desktop, name="impressoes_desktop"),
    path("impressoes/padroes/", views.impressoes_padroes, name="impressoes_padroes"),
    path("impressoes/nova/", views.impressao_form, name="impressao_nova"),
    path("impressoes/<int:pk>/editar/", views.impressao_form, name="impressao_editar"),
    path("impressoes/modelos-etiqueta/novo/", views.modelo_etiqueta_form, name="modelo_etiqueta_novo"),
    path("impressoes/modelos-etiqueta/<int:pk>/teste.json", views.modelo_etiqueta_teste, name="modelo_etiqueta_teste"),
    path("impressoes/modelos-etiqueta/<int:pk>/editar/", views.modelo_etiqueta_form, name="modelo_etiqueta_editar"),
]
