# Generated by Django 6.0.6 on 2026-07-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_alter_eventoentradasincronizacao_status_and_more'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['empresa_id', 'razao_social']},
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='empresas.empresa'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['empresa', 'razao_social'], name='fornec_empresa_razao_idx'),
        ),
    ]
