# Generated by Django 6.0.6 on 2026-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_atribuir_empresa_fornecedores_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=60, verbose_name='Bairro fiscal'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP fiscal'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, max_length=7, verbose_name='Código IBGE do município'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, verbose_name='Complemento fiscal'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='indicador_ie',
            field=models.CharField(blank=True, choices=[('1', 'Contribuinte de ICMS'), ('2', 'Contribuinte isento de inscrição'), ('9', 'Não contribuinte')], default='', max_length=1, verbose_name='Indicador de IE'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Logradouro fiscal'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='municipio',
            field=models.CharField(blank=True, max_length=60, verbose_name='Município fiscal'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número fiscal'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF fiscal'),
        ),
    ]
