# Generated by Django 6.0.6 on 2026-07-01 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='data_conferencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='observacao_conferencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='caixa',
            name='usuario_conferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_conferidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caixa',
            name='valor_conferido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('CONFERIDO', 'Conferido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20),
        ),
    ]
