# Generated by Django 6.0.6 on 2026-07-03 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_filial_codigo_municipio_ibge_filial_municipio_and_more'),
        ('pdv', '0003_acessopdvnuvem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalPdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('permite_modo_offline', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_conexao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminais_pdv', to='empresas.filial')),
            ],
            options={
                'ordering': ['filial__nome', 'nome'],
                'unique_together': {('filial', 'nome')},
            },
        ),
    ]
