# Generated by Django 6.0.6 on 2026-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_terminalpdv_chave_api_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalpdv',
            name='emite_documento_fiscal',
            field=models.BooleanField(default=True),
        ),
    ]
