# Generated by Django 6.0.6 on 2026-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0006_terminalpdv_emite_documento_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalpdv',
            name='modo_integracao_tef',
            field=models.CharField(choices=[('DESKTOP_BRIDGE', 'App desktop / bridge local'), ('API', 'API direta da operadora'), ('POS_INTEGRADO', 'POS/SmartPOS integrado'), ('MANUAL', 'Manual sem retorno automatico')], default='DESKTOP_BRIDGE', max_length=30),
        ),
        migrations.AddField(
            model_name='terminalpdv',
            name='provedor_tef',
            field=models.CharField(choices=[('NAO_CONFIGURADO', 'Nao configurado'), ('SITEF', 'SiTef / Software Express'), ('CIELO', 'Cielo'), ('STONE', 'Stone'), ('GETNET', 'Getnet'), ('PAGBANK', 'PagBank / PagSeguro'), ('REDE', 'Rede'), ('OUTRO', 'Outro adaptador')], default='NAO_CONFIGURADO', max_length=30),
        ),
    ]
