# Generated by Django 6.0.6 on 2026-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_terminalpdv_modo_integracao_tef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalpdv',
            name='modelo_balanca',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='terminalpdv',
            name='porta_balanca',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='terminalpdv',
            name='protocolo_balanca',
            field=models.CharField(choices=[('NAO_CONFIGURADO', 'Nao configurado'), ('SERIAL', 'Serial RS-232/USB'), ('TCP_IP', 'TCP/IP'), ('ARQUIVO_TXT', 'Arquivo texto local'), ('OUTRO', 'Outro protocolo')], default='NAO_CONFIGURADO', max_length=30),
        ),
        migrations.AddField(
            model_name='terminalpdv',
            name='usa_balanca',
            field=models.BooleanField(default=False),
        ),
    ]
