# Generated by Django 6.0.6 on 2026-07-07 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0008_terminalpdv_modelo_balanca_terminalpdv_porta_balanca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalpdv',
            name='licenca_liberada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminalpdv',
            name='licenca_liberada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminais_pdv_liberados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terminalpdv',
            name='observacao_licenca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='terminalpdv',
            name='status_licenca',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('LIBERADA', 'Liberada'), ('BLOQUEADA', 'Bloqueada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
    ]
