# Generated by Django 6.0.6 on 2026-07-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0009_terminalpdv_licenca_liberada_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDispositivoTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('mensagem', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ocorrido_em', models.DateTimeField(blank=True, null=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_dispositivo', to='pdv.terminalpdv')),
            ],
            options={
                'ordering': ['-recebido_em'],
                'indexes': [models.Index(fields=['terminal', '-recebido_em'], name='pdv_eventod_termina_624b1d_idx'), models.Index(fields=['tipo', 'status'], name='pdv_eventod_tipo_439460_idx')],
            },
        ),
    ]
