# Generated by Django 6.0.6 on 2026-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0010_eventodispositivoterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalpdv',
            name='bloquear_atualizacoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terminalpdv',
            name='canal_atualizacao',
            field=models.CharField(choices=[('ESTAVEL', 'Estavel'), ('PILOTO', 'Piloto')], default='ESTAVEL', max_length=20),
        ),
    ]
