# Generated by Django 6.0.6 on 2026-07-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0011_terminalpdv_bloquear_atualizacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodispositivoterminal',
            name='evento_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventodispositivoterminal',
            constraint=models.UniqueConstraint(fields=('terminal', 'evento_id'), name='uniq_evento_dispositivo_terminal'),
        ),
    ]
