# Generated by Django 6.0.6 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0012_eventodispositivoterminal_evento_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalpdv',
            name='modo_integracao_tef',
            field=models.CharField(choices=[('DESKTOP_BRIDGE', 'App desktop / bridge local'), ('API', 'API direta da operadora'), ('POS_INTEGRADO', 'POS/SmartPOS integrado'), ('MANUAL', 'Manual sem retorno automático')], default='DESKTOP_BRIDGE', max_length=30),
        ),
        migrations.AlterField(
            model_name='terminalpdv',
            name='protocolo_balanca',
            field=models.CharField(choices=[('NAO_CONFIGURADO', 'Não configurado'), ('SERIAL', 'Serial RS-232/USB'), ('TCP_IP', 'TCP/IP'), ('ARQUIVO_TXT', 'Arquivo texto local'), ('OUTRO', 'Outro protocolo')], default='NAO_CONFIGURADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='terminalpdv',
            name='provedor_tef',
            field=models.CharField(choices=[('NAO_CONFIGURADO', 'Não configurado'), ('SITEF', 'SiTef / Software Express'), ('CIELO', 'Cielo'), ('STONE', 'Stone'), ('GETNET', 'Getnet'), ('PAGBANK', 'PagBank / PagSeguro'), ('REDE', 'Rede'), ('OUTRO', 'Outro adaptador')], default='NAO_CONFIGURADO', max_length=30),
        ),
    ]
