# Generated by Django 6.0.6 on 2026-07-28 15:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0012_alter_empresa_politica_conflito_sincronizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoWebhookAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado'), ('IGNORADO', 'Ignorado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('erro', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('valor_matriz', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_por_filial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_por_terminal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_tolerancia', models.PositiveSmallIntegerField(default=7)),
                ('dias_aviso', models.PositiveSmallIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContratoLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('AVISO', 'Próximo do vencimento'), ('TOLERANCIA', 'Em tolerância'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('validade_em', models.DateField(blank=True, null=True)),
                ('tolerancia_ate', models.DateTimeField(blank=True, null=True)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=80)),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=80)),
                ('cobranca_automatica', models.BooleanField(default=True)),
                ('bloqueio_automatico', models.BooleanField(default=True)),
                ('motivo_bloqueio', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_licenca', to='empresas.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='licenciamento.planocomercial')),
            ],
            options={
                'ordering': ['empresa__nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='EstadoLicencaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('AVISO', 'Próximo do vencimento'), ('TOLERANCIA', 'Em tolerância'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('valida_ate', models.DateTimeField(blank=True, null=True)),
                ('tolerancia_ate', models.DateTimeField(blank=True, null=True)),
                ('ultima_sincronizacao_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_fatura_vencimento', models.DateField(blank=True, null=True)),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('url_pagamento', models.URLField(blank=True)),
                ('mensagem', models.TextField(blank=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('assinatura', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_licenca_local', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='InstalacaoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('ultima_consulta_em', models.DateTimeField(blank=True, null=True)),
                ('versao_sistema', models.CharField(blank=True, max_length=40)),
                ('ip_ultimo_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalacoes_licenca', to='empresas.empresa')),
            ],
            options={
                'ordering': ['empresa__nome_fantasia', 'nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ConcessaoLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('AVISO', 'Próximo do vencimento'), ('TOLERANCIA', 'Em tolerância'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('emitida_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('valida_ate', models.DateTimeField()),
                ('tolerancia_ate', models.DateTimeField(blank=True, null=True)),
                ('assinatura', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('instalacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concessao', to='licenciamento.instalacaolocal')),
            ],
        ),
        migrations.CreateModel(
            name='FaturaLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDA', 'Recebida'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('ESTORNADA', 'Estornada')], default='PENDENTE', max_length=20)),
                ('referencia_externa', models.CharField(max_length=120, unique=True)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('invoice_url', models.URLField(blank=True)),
                ('bank_slip_url', models.URLField(blank=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='licenciamento.contratolicenca')),
            ],
            options={
                'ordering': ['-competencia', '-vencimento'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'competencia'), name='licenca_fatura_competencia_unica')],
            },
        ),
    ]
