# Generated by Django 6.0.6 on 2026-07-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadolicencalocal',
            name='offline_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
