# Generated by Django 6.0.6 on 2026-07-28 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_alter_empresa_politica_conflito_sincronizacao'),
        ('licenciamento', '0002_estadolicencalocal_offline_ate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadolicencalocal',
            name='liberacao_emergencial_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadolicencalocal',
            name='liberacao_emergencial_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AutorizacaoEmergencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('desafio_id', models.UUIDField(unique=True)),
                ('nonce_hash', models.CharField(max_length=64)),
                ('motivo', models.TextField()),
                ('emitida_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('valida_ate', models.DateTimeField()),
                ('usada_em', models.DateTimeField(blank=True, null=True)),
                ('reconciliada_em', models.DateTimeField(blank=True, null=True)),
                ('assinatura', models.TextField()),
                ('ip_emissao', models.GenericIPAddressField(blank=True, null=True)),
                ('emitida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_licenca_emitidas', to=settings.AUTH_USER_MODEL)),
                ('instalacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_emergenciais', to='licenciamento.instalacaolocal')),
            ],
            options={
                'ordering': ['-emitida_em'],
            },
        ),
        migrations.CreateModel(
            name='DesafioLiberacaoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nonce_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_licenca', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LiberacaoEmergencialLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacao_id', models.UUIDField(unique=True)),
                ('instalacao_id', models.UUIDField()),
                ('motivo', models.TextField()),
                ('emitida_em', models.DateTimeField()),
                ('valida_ate', models.DateTimeField()),
                ('aplicada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('sincronizada_em', models.DateTimeField(blank=True, null=True)),
                ('assinatura', models.TextField()),
                ('desafio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='liberacao', to='licenciamento.desafioliberacaolocal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liberacoes_emergenciais', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-aplicada_em'],
            },
        ),
    ]
